# Feature Transformation

In [10]:
%load_ext autoreload
%autoreload 2
from src.postgresql import get_engine
import pandas as pd
pd.set_option("display.max_columns", 100)
pd.set_option('display.max_rows', 50)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
from src.redis.redis_client import RedisClient

r = RedisClient.get_instance()

In [12]:
engine = get_engine()

## Transform Hero Features

In [13]:
df_hero_features = pd.read_sql(
    "SELECT * FROM hero_features",
    con=engine
)

df_hero_features

         match_id                                         hero_picks
0      6002092367  [Kunkka, Sven, Ancient Apparition, Mars, Shado...
1      6003543228  [Spectre, Void Spirit, Mars, Enchantress, Elde...
2      6061828036  [Hoodwink, Disruptor, Magnus, Puck, Spectre, L...
3      6067799696  [Spectre, Magnus, Nyx Assassin, Mirana, Dragon...
4      6074484431  [Dark Willow, Drow Ranger, Kunkka, Broodmother...
...           ...                                                ...
99320  8230206445  [Slark, Leshrac, Mars, Muerta, Silencer, Abadd...
99321  8230245010  [Vengeful Spirit, Tinker, Kunkka, Phoenix, Mor...
99322  8230270883  [Shadow Shaman, Shadow Fiend, Leshrac, Abaddon...
99323  8230283967  [Gyrocopter, Invoker, Beastmaster, Tusk, Silen...
99324  8230422889  [Drow Ranger, Hoodwink, Axe, Phoenix, Arc Ward...

[99325 rows x 2 columns]

### One-Hot-Encoding

In [14]:
from sklearn.preprocessing import MultiLabelBinarizer

In [15]:
from constants.constants import HERO_DICT

In [16]:
ALL_HEROES = list(HERO_DICT.values())
ALL_HEROES

['Anti-Mage',
 'Axe',
 'Bane',
 'Bloodseeker',
 'Crystal Maiden',
 'Drow Ranger',
 'Earthshaker',
 'Juggernaut',
 'Mirana',
 'Morphling',
 'Shadow Fiend',
 'Phantom Lancer',
 'Puck',
 'Pudge',
 'Razor',
 'Sand King',
 'Storm Spirit',
 'Sven',
 'Tiny',
 'Vengeful Spirit',
 'Windranger',
 'Zeus',
 'Kunkka',
 'Lina',
 'Lion',
 'Shadow Shaman',
 'Slardar',
 'Tidehunter',
 'Witch Doctor',
 'Lich',
 'Riki',
 'Enigma',
 'Tinker',
 'Sniper',
 'Necrophos',
 'Warlock',
 'Beastmaster',
 'Queen of Pain',
 'Venomancer',
 'Faceless Void',
 'Wraith King',
 'Death Prophet',
 'Phantom Assassin',
 'Pugna',
 'Templar Assassin',
 'Viper',
 'Luna',
 'Dragon Knight',
 'Dazzle',
 'Clockwerk',
 'Leshrac',
 "Nature's Prophet",
 'Lifestealer',
 'Dark Seer',
 'Clinkz',
 'Omniknight',
 'Enchantress',
 'Huskar',
 'Night Stalker',
 'Broodmother',
 'Bounty Hunter',
 'Weaver',
 'Jakiro',
 'Batrider',
 'Chen',
 'Spectre',
 'Ancient Apparition',
 'Doom',
 'Ursa',
 'Spirit Breaker',
 'Gyrocopter',
 'Alchemist',
 'Invoker',
 'Silencer',
 'Outworld Devourer',
 'Lycan',
 'Brewmaster',
 'Shadow Demon',
 'Lone Druid',
 'Chaos Knight',
 'Meepo',
 'Treant Protector',
 'Ogre Magi',
 'Undying',
 'Rubick',
 'Disruptor',
 'Nyx Assassin',
 'Naga Siren',
 'Keeper of the Light',
 'Io',
 'Visage',
 'Slark',
 'Medusa',
 'Troll Warlord',
 'Centaur Warrunner',
 'Magnus',
 'Timbersaw',
 'Bristleback',
 'Tusk',
 'Skywrath Mage',
 'Abaddon',
 'Elder Titan',
 'Legion Commander',
 'Techies',
 'Ember Spirit',
 'Earth Spirit',
 'Underlord',
 'Terrorblade',
 'Phoenix',
 'Oracle',
 'Winter Wyvern',
 'Arc Warden',
 'Monkey King',
 'Dark Willow',
 'Pangolier',
 'Grimstroke',
 'Hoodwink',
 'Void Spirit',
 'Snapfire',
 'Mars',
 'Ring Master',
 'Dawnbreaker',
 'Marci',
 'Primal Beast',
 'Muerta',
 'Kez']

In [18]:
mlb = MultiLabelBinarizer(classes=ALL_HEROES)
hero_matrix = mlb.fit_transform(df_hero_features['hero_picks'])
hero_features = pd.DataFrame(hero_matrix, columns=mlb.classes_)
hero_features.insert(0, 'match_id', df_hero_features['match_id'].values)

In [19]:
hero_features

,match_id,Anti-Mage,Axe,Bane,Bloodseeker,Crystal Maiden,Drow Ranger,Earthshaker,Juggernaut,Mirana,Morphling,Shadow Fiend,Phantom Lancer,Puck,Pudge,Razor,Sand King,Storm Spirit,Sven,Tiny,Vengeful Spirit,Windranger,Zeus,Kunkka,Lina,Lion,Shadow Shaman,Slardar,Tidehunter,Witch Doctor,Lich,Riki,Enigma,Tinker,Sniper,Necrophos,Warlock,Beastmaster,Queen of Pain,Venomancer,Faceless Void,Wraith King,Death Prophet,Phantom Assassin,Pugna,Templar Assassin,Viper,Luna,Dragon Knight,Dazzle,...,Brewmaster,Shadow Demon,Lone Druid,Chaos Knight,Meepo,Treant Protector,Ogre Magi,Undying,Rubick,Disruptor,Nyx Assassin,Naga Siren,Keeper of the Light,Io,Visage,Slark,Medusa,Troll Warlord,Centaur Warrunner,Magnus,Timbersaw,Bristleback,Tusk,Skywrath Mage,Abaddon,Elder Titan,Legion Commander,Techies,Ember Spirit,Earth Spirit,Underlord,Terrorblade,Phoenix,Oracle,Winter Wyvern,Arc Warden,Monkey King,Dark Willow,Pangolier,Grimstroke,Hoodwink,Void Spirit,Snapfire,Mars,Ring Master,Dawnbreaker,Marci,Primal Beast,Muerta,Kez
0,6002092367,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
1,6003543228,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
2,6061828036,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,6067799696,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,6074484431,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99320,8230206445,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
99321,8230245010,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
99322,8230270883,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
99323,8230283967,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
99324,8230422889,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0

### Text Vector Embedding

# to do

## Team Features

In [20]:
df_team_features = pd.read_sql(
    "SELECT * FROM team_features",
    con=engine
)

df_team_features

         match_id  radiant_dire_matchup  radiant_win_rate  dire_win_rate
0      8230722475              0.333333               0.5            0.7
1      8230693148              0.625000               0.6            0.6
2      8230654189              0.714286               0.7            0.6
3      8230617184              0.333333               0.6            0.6
4      8230607886              0.500000               0.2            0.6
...           ...                   ...               ...            ...
99320  8230586103              0.450000               0.5            0.2
99321  8230631979              0.450000               0.5            0.3
99322  8230656847              0.600000               0.7            0.4
99323  8230677659              0.350000               0.4            0.8
99324  8230701740              0.600000               0.7            0.5

[99325 rows x 4 columns]

### Player Hero Features

In [21]:
df_player_hero_features = pd.read_sql(
    "SELECT * FROM player_hero_features",
    con=engine
)

df_player_hero_features

,match_id,player_hero_0_win_rate,player_hero_1_win_rate,player_hero_2_win_rate,player_hero_3_win_rate,player_hero_4_win_rate,player_hero_128_win_rate,player_hero_129_win_rate,player_hero_130_win_rate,player_hero_131_win_rate,player_hero_132_win_rate
0,5999176266,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.500000,0.500000,0.500000,0.50
1,5999201501,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.500000,0.500000,0.500000,0.50
2,5999214195,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.500000,0.500000,0.500000,0.50
3,5999249937,0.500000,0.500000,0.500000,1.00,0.5,0.500000,0.000000,0.500000,0.500000,0.50
4,5999283181,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.500000,0.500000,0.500000,0.50
...,...,...,...,...,...,...,...,...,...,...,...
99320,8230656847,0.450000,0.538462,0.400000,0.40,0.5,0.384615,0.350000,0.500000,0.600000,0.65
99321,8230677659,0.250000,0.350000,0.625000,0.45,0.6,0.625000,0.600000,1.000000,1.000000,0.00
99322,8230693148,0.777778,0.714286,0.692308,1.00,0.5,0.588235,0.500000,0.600000,0.833333,0.50
99323,8230701740,0.642857,0.500000,0.384615,0.70,0.4,0.300000,0.666667,0.300000,0.550000,0.50
99324,8230722475,0.600000,0.550000,0.600000,0.75,0.4,0.800000,0.769231,0.714286,0.500000,0.80

## Combined Features

In [22]:
merged_df = pd.merge(
    hero_features,
    df_player_hero_features,
    on='match_id',
    how='inner'
)

final_df = pd.merge(
    merged_df,
    df_team_features,
    on='match_id',
    how='inner'
)

final_df

,match_id,Anti-Mage,Axe,Bane,Bloodseeker,Crystal Maiden,Drow Ranger,Earthshaker,Juggernaut,Mirana,Morphling,Shadow Fiend,Phantom Lancer,Puck,Pudge,Razor,Sand King,Storm Spirit,Sven,Tiny,Vengeful Spirit,Windranger,Zeus,Kunkka,Lina,Lion,Shadow Shaman,Slardar,Tidehunter,Witch Doctor,Lich,Riki,Enigma,Tinker,Sniper,Necrophos,Warlock,Beastmaster,Queen of Pain,Venomancer,Faceless Void,Wraith King,Death Prophet,Phantom Assassin,Pugna,Templar Assassin,Viper,Luna,Dragon Knight,Dazzle,...,Io,Visage,Slark,Medusa,Troll Warlord,Centaur Warrunner,Magnus,Timbersaw,Bristleback,Tusk,Skywrath Mage,Abaddon,Elder Titan,Legion Commander,Techies,Ember Spirit,Earth Spirit,Underlord,Terrorblade,Phoenix,Oracle,Winter Wyvern,Arc Warden,Monkey King,Dark Willow,Pangolier,Grimstroke,Hoodwink,Void Spirit,Snapfire,Mars,Ring Master,Dawnbreaker,Marci,Primal Beast,Muerta,Kez,player_hero_0_win_rate,player_hero_1_win_rate,player_hero_2_win_rate,player_hero_3_win_rate,player_hero_4_win_rate,player_hero_128_win_rate,player_hero_129_win_rate,player_hero_130_win_rate,player_hero_131_win_rate,player_hero_132_win_rate,radiant_dire_matchup,radiant_win_rate,dire_win_rate
0,6002092367,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0.500000,0.50,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,1.000000,0.500000,0.000000,0.0,1.0
1,6003543228,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0.500000,0.50,0.500000,0.500000,0.500000,1.000000,0.000000,0.500000,0.500000,1.000000,0.500000,0.5,0.5
2,6061828036,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.500000,0.00,0.555556,0.333333,0.500000,0.500000,1.000000,0.500000,1.000000,1.000000,0.500000,0.5,0.5
3,6067799696,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.500000,0.50,0.500000,1.000000,1.000000,0.400000,0.857143,0.500000,0.428571,0.538462,0.666667,0.4,0.5
4,6074484431,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1.000000,0.50,1.000000,0.666667,0.857143,0.500000,0.000000,0.333333,0.400000,0.500000,1.000000,0.8,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99320,8230206445,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0.444444,0.50,0.550000,0.700000,0.400000,0.500000,0.700000,1.000000,0.833333,0.428571,1.000000,0.5,0.4
99321,8230245010,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0.50,0.500000,0.312500,0.500000,1.000000,0.500000,1.000000,1.000000,0.500000,1.000000,1.0,1.0
99322,8230270883,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1.000000,0.30,0.700000,0.500000,0.578947,0.571429,0.750000,0.384615,0.750000,1.000000,0.600000,0.3,0.6
99323,8230283967,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0.600000,0.75,0.000000,0.650000,0.500000,0.333333,0.600000,0.333333,0.000000,0.562500,0.333333,0.5,0.4
99324,8230422889,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.550000,0.60,0.400000,0.650000,0.400000,0.500000,0.600000,0.400000,0.500000,0.437500,0.450000,0.4,0.6

In [29]:
import os
from src.config import ROOT_DIR

output_dir = f'{ROOT_DIR}/data/processed/'
output_file_path = os.path.join(output_dir, "merged_features_data.csv")

In [30]:
## Store to csv for now
final_df.to_csv(output_file_path, index=False)