# OpenDota API

Exploring Endpoints from OpenDota's API, which contains data that is more structured than Steam's WebAPI albeit some missing information.

In [1]:
%load_ext autoreload
%autoreload 2
import requests
import pandas as pd
from datetime import datetime as dt
from src.fetch_data.opendota_api import get_opendota_df
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", 100)
pd.set_option('display.max_rows', 200)

## Exploring Tables using Dota 2 API

In [2]:
df_hero_stats = await get_opendota_df('heroStats')
df_team_stats = await get_opendota_df('teams')
df_pro_players = await get_opendota_df('proPlayers')
df_pro_matches = await get_opendota_df('proMatches')

## 1. Hero Stats

In [3]:
df_hero_stats

,id,name,primary_attr,attack_type,roles,img,icon,base_health,base_health_regen,base_mana,base_mana_regen,base_armor,base_mr,base_attack_min,base_attack_max,base_str,base_agi,base_int,str_gain,agi_gain,int_gain,attack_range,projectile_speed,attack_rate,base_attack_time,attack_point,move_speed,turn_rate,cm_enabled,legs,day_vision,night_vision,localized_name,1_pick,1_win,2_pick,2_win,3_pick,3_win,4_pick,4_win,5_pick,5_win,6_pick,6_win,7_pick,7_win,8_pick,8_win,turbo_picks,turbo_picks_trend,turbo_wins,turbo_wins_trend,pro_pick,pro_win,pro_ban,pub_pick,pub_pick_trend,pub_win,pub_win_trend
0,1,npc_dota_hero_antimage,agi,Melee,"[Carry, Escape, Nuker]",/apps/dota2/images/dota_react/heroes/antimage....,/apps/dota2/images/dota_react/heroes/icons/ant...,120,1.00,75,0.00,1,25,29,33,19,24,12,1.6,2.8,1.8,150,0,1.4,100,0.300,310,NaN,True,2,1800,800,Anti-Mage,19555,9581,58968,29113,83287,40920,83258,41243,60945,29967,34253,17084,18082,8823,7989,3798,172040,"[32678, 32607, 27310, 25277, 23747, 25029, 5392]",86968,"[16586, 16502, 13801, 12850, 11951, 12558, 2720]",118,59,310,405750,"[75565, 76779, 65267, 61654, 55916, 56674, 13895]",199770,"[37340, 37687, 32226, 30284, 27695, 27681, 6857]"
1,2,npc_dota_hero_axe,str,Melee,"[Initiator, Durable, Disabler, Carry]",/apps/dota2/images/dota_react/heroes/axe.png?,/apps/dota2/images/dota_react/heroes/icons/axe...,120,2.50,75,0.00,0,25,30,34,25,20,18,2.8,1.7,1.6,150,900,1.7,100,0.400,315,NaN,True,2,1800,800,Axe,27948,15050,85141,45485,125018,65456,131802,68747,101429,51960,60356,30978,34632,17564,16679,8463,219671,"[40969, 41362, 34511, 32620, 30823, 32050, 7336]",116718,"[21704, 21915, 18349, 17309, 16369, 17169, 3903]",326,168,442,630494,"[115818, 118835, 99138, 94684, 88538, 90530, 2...",328764,"[60367, 61936, 51745, 49443, 46265, 47110, 11898]"
2,3,npc_dota_hero_bane,all,Ranged,"[Support, Disabler, Nuker, Durable]",/apps/dota2/images/dota_react/heroes/bane.png?,/apps/dota2/images/dota_react/heroes/icons/ban...,120,0.25,75,0.00,1,25,-1,5,23,23,23,2.7,2.7,2.7,400,900,1.7,100,0.300,305,NaN,True,4,1800,1200,Bane,4460,2141,11672,5615,15839,7680,16347,8078,12362,6143,7557,3853,4503,2342,3046,1526,55231,"[10411, 10505, 8531, 8293, 7594, 8095, 1802]",26492,"[4995, 5022, 4078, 3934, 3665, 3912, 886]",113,61,69,92049,"[16290, 17002, 14624, 13985, 12863, 13779, 3506]",45337,"[8024, 8368, 7209, 6857, 6314, 6838, 1727]"
3,4,npc_dota_hero_bloodseeker,agi,Melee,"[Carry, Disabler, Nuker, Initiator]",/apps/dota2/images/dota_react/heroes/bloodseek...,/apps/dota2/images/dota_react/heroes/icons/blo...,120,0.25,75,0.00,2,25,35,41,24,24,17,2.7,3.1,2.0,150,900,1.7,100,0.430,285,NaN,True,2,1800,800,Bloodseeker,10950,5571,22222,11374,26388,13648,24061,12599,17796,9396,10219,5405,5664,2941,2481,1253,80349,"[15098, 14849, 12810, 11976, 11274, 11643, 2699]",39784,"[7535, 7299, 6336, 6003, 5548, 5735, 1328]",59,32,48,147141,"[27132, 27685, 23518, 22226, 20318, 20611, 5651]",75947,"[14032, 14291, 12157, 11380, 10545, 10614, 2928]"
4,5,npc_dota_hero_crystal_maiden,int,Ranged,"[Support, Disabler, Nuker]",/apps/dota2/images/dota_react/heroes/crystal_m...,/apps/dota2/images/dota_react/heroes/icons/cry...,120,0.25,75,0.00,0,25,30,36,17,16,18,2.2,1.6,3.3,600,900,1.7,100,0.450,280,NaN,True,2,1800,800,Crystal Maiden,23320,12177,61412,31501,80561,40371,77257,38113,57464,28165,33680,16312,18395,8801,8787,4147,185449,"[34576, 34799, 29029, 27704, 26165, 27179, 5997]",94660,"[17828, 17770, 14784, 14014, 13298, 13942, 3024]",215,102,37,397408,"[72684, 73859, 63031, 59712, 55799, 57702, 14621]",198451,"[36206, 36789, 31359, 29942, 28019, 28974, 7162]"
5,6,npc_dota_hero_drow_ranger,agi,Ranged,"[Carry, Disabler, Pusher]",/apps/dota2/images/dota_react/heroes/drow_rang...,/apps/dota2/images/dota_react/heroes/icons/dro...,120,0.25,75,0.00,0,25,29,36,16,20,15,1.9,2.9,1.4,625,1250,1.7,100,0.500,310,0.7,True,2,1800,800,Drow Ranger,24304,11811,58815,29012,76015,38030,73490,36888,52214,26331,28494,14354,13960,6913,4971,2374,245345,"[45281, 46121, 38370, 36562, 34717, 36267, 8027]",131963,"[24504, 24761, 20527, 19775, 18755, 19436, 4205]",138,58,145,374484,"[68685, 70062, 59461, 56625, 52255, 53778, 13618]",186447,"[34152, 34834, 29780, 28201, 26108, 26650, 6722]"
6,7,npc_dota_hero_earthshaker,str,Melee,"[Support, Initiator, Disabler, Nuker]",/apps/dota2/images/dota_react/heroes/earthshak...,/apps/dota2/images/dota_react/heroes/icons/ear...,120,1.00,75,0.00,2,25,27,37,22,12,18,3.7,1.4,2.1,150,0,1.7,100,0.467,315,0.9,True,2,1800,800,Earthshaker,26010,12670,68578,33029,95412,46197,103243,50706,83665,41315,53267,26286,32163,16183,17759,9054,268623,"[49550, 49325, 42581, 39780, 38370, 40510, 8507]",127288,"[23649, 23400, 20096, 18786, 18113, 19162, 4082]",255,135,224,527654,"[94110, 97584, 84484, 79140, 74527, 78306, 19503]",258856,"[46428, 47821, 41350, 38913, 36588, 38130, 9626]"
7,8,npc_dota_hero_juggernaut,agi,Melee,"[Carry, Pusher, Escape]",/apps/dota2/images/dota_react/heroes/juggernau...,/apps/dota2/images/dota_react/heroes/icons/jug...,120,0.50,75,0.00,0,25,22,24,20,34,14,2.0,2.8,1.4,150,0,1.4,110,0.330,300,NaN,True,2,1800,800,Juggernaut,29020,14907,81355,42010,117691,61537,120582,62955,89013,46597,48841,25324,24893,12769,8436,4115,300205,"[56384, 56531, 47317, 44491, 41848, 43500, 10134]",156087,"[29484, 29520, 24530, 23101, 21882, 22371, 5199]",164,80,153,573025,"[105851, 108642, 91130, 86209, 79644, 79762, 2...",297114,"[54994, 56579, 47030, 44899, 41122, 41306, 11184]"
8,9,npc_dota_hero_mirana,all,Ranged,"[Carry, Support, Escape, Nuker, Disabler]",/apps/dota2/images/dota_react/heroes/mirana.png?,/apps/dota2/images/dota_react/heroes/icons/mir...,120,0.25,75,0.40,-2,25,-2,2,18,26,22,1.9,2.5,1.4,630,900,1.7,100,0.350,285,NaN,True,2,1800,800,Mirana,10628,5089,36994,17487,61784,29005,72525,33682,61734,28418,41289,19014,24936,11517,15968,7444,131094,"[22289, 22898, 18759, 17670, 18178, 24970, 6330]",64155,"[10950, 11221, 9235, 8621, 8832, 12126, 3170]",313,159,289,351110,"[57252, 60018, 51102, 47657, 49197, 67536, 18348]",164024,"[26782, 28167, 24090, 22405, 23189, 30961, 8430]"
9,10,npc_dota_hero_morphling,agi,Ranged,"[Carry, Escape, Durable, Nuker, Disabler]",/apps/dota2/images/dota_react/heroes/morphling...,/apps/dota2/images/dota_react/heroes/icons/mor...,120,0.50,75,0.50,-2,25,12,21,23,24,19,3.2,3.9,1.8,350,1300,1.5,100,0.500,285,0.7,True,0,1800,800,Morphling,7250,3309,20982,9228,31734,13833,36253,15905,32454,14244,23460,10521,16419,7520,13897,6397,94520,"[17357, 17415, 14781, 13342, 12949, 15538, 3138]",42142,"[7673, 7707, 6637, 5919, 5830, 7038, 1338]",203,92,280,196073,"[34957, 35254, 30318, 28827, 27309, 31650, 7758]",87057,"[15763, 15691, 13371, 12898, 12161, 13764, 3409]"
10,11,npc_dota_hero_nevermore,agi,Ranged,"[Carry, Nuker]",/apps/dota2/images/dota_react/heroes/nevermore...,/apps/dota2/images/dota_react/heroes/icons/nev...,120,0.25,75,0.30,1,25,16,22,19,25,18,2.7,3.5,2.2,525,1200,1.6,100,0.500,305,0.9,True,0,1800,800,Shadow Fiend,26498,12806,71716,34993,101661,49224,107274,51889,85865,41460,53309,25792,31609,15432,19429,9626,304178,"[56327, 55361, 48518, 44684, 43984, 46823, 8481]",142007,"[26240, 25836, 22615, 20789, 20514, 21984, 4029]",352,193,585,548971,"[99241, 99942, 87187, 82350, 78937, 82780, 18534]",265682,"[47935, 48251, 42150, 39802, 38318, 40169, 9057]"
11,12,npc_dota_hero_phantom_lancer,agi,Melee,"[Carry, Escape, Pusher, Nuker]",/apps/dota2/images/dota_react/heroes/phantom_l...,/apps/dota2/images/dota_react/heroes/icons/pha...,120,1.50,75,0.00,0,25,26,36,19,26,21,2.2,2.8,1.8,225,900,1.7,110,0.500,285,NaN,True,2,1800,800,Phantom Lancer,11857,5797,28652,13795,32582,15269,26981,12443,16287,7424,8030,3549,3674,1607,1420,629,98469,"[19155, 18670, 15301, 14478, 13605, 14039, 3221]",49379,"[9562, 9455, 7707, 7182, 6857, 7024, 1592]",29,11,142,154979,"[30001, 29734, 24799, 23132, 21098, 20926, 5289]",72954,"[14136, 14165, 11619, 10849, 9877, 9871, 2437]"
12,13,npc_dota_hero_puck,int,Ranged,"[Initiator, Disabler, Escape, Nuker]",/apps/dota2/images/dota_react/heroes/puck.png?,/apps/dota2/images/dota_react/heroes/icons/puc...,120,0.50,75,0.50,0,25,22,30,17,14,23,2.4,2.5,3.8,550,900,1.7,100,0.500,290,0.9,True,2,1800,800,Puck,6865,3155,21496,10114,36864,17662,47301,22741,44574,21653,31911,15703,21049,10498,14280,7095,78589,"[15133, 14536, 12409, 11366, 10684, 11961, 2500]",36260,"[6935, 6564, 5831, 5299, 4999, 5475, 1157]",216,115,460,243856,"[44712, 45168, 39054, 36323, 33453, 36228, 8918]",117919,"[21627, 21720, 18878, 17569, 16252, 17494, 4379]"
13,14,npc_dota_hero_pudge,str,Melee,"[Disabler, Initiator, Durable, Nuker]",/apps/dota2/images/dota_react/heroes/pudge.png?,/apps/dota2/images/dota_react/heroes/icons/pud...,120,2.50,75,0.00,0,25,45,51,25,11,16,3.0,1.4,1.8,175,0,1.7,100,0.500,280,0.7,True,2,1800,800,Pudge,44215,23077,129548,66939,177090,90799,170903,87105,126846,64013,78055,39073,47603,23686,29936,14749,690571,"[128213, 127886, 108478, 102236, 98075, 102716...",346580,"[64317, 63782, 54330, 51332, 49181, 51989, 11649]",533,282,551,878751,"[162231, 163575, 137264, 130518, 122913, 12876...",448029,"[82690, 83354, 70135, 66423, 62732, 65608, 17087]"
14,15,npc_dota_hero_razor,agi,Ranged,"[Carry, Durable, Nuker, Pusher]",/apps/dota2/images/dota_react/heroes/razor.png?,/apps/dota2/images/dota_react/heroes/icons/raz...,120,1.00,75,0.00,0,25,23,25,22,24,21,2.8,2.8,2.2,475,2000,1.7,100,0.300,280,NaN,True,0,1800,800,Razor,13199,6799,31060,15995,41612,21354,45487,23298,36815,18780,23688,11892,14728,7387,7851,3929,107021,"[19810, 20090, 16673, 15852, 15086, 15768, 3742]",56189,"[10459, 10621, 8739, 8329, 7933, 8176, 1932]",132,60,162,242150,"[43529, 45194, 37612, 36619, 34381, 34876, 9939]",123565,"[22204, 23059, 19163, 18860, 17423, 17779, 5077]"
15,16,npc_dota_hero_sand_king,all,Melee,"[Initiator, Disabler, Support, Nuker, Escape]",/apps/dota2/images/dota_react/heroes/sand_king...,/apps/dota2/images/dota_react/heroes/icons/san...,120,0.25,75,0.00,1,25,7,15,21,19,17,2.3,1.8,1.8,150,900,1.7,110,0.530,290,NaN,True,6,1800,800,Sand King,13164,7084,36856,19443,56403,29722,68149,35633,62252,32628,44749,23413,29955,15599,23033,11881,122142,"[21920, 22316, 18420, 18032, 17333, 19712, 4409]",65631,"[11817, 12116, 9865, 9680, 9347, 10461, 2345]",408,228,637,357011,"[64625, 64692, 55057, 53368, 49981, 55287, 14001]",187526,"[33829, 33899, 28870, 28131, 26373, 29104, 7320]"
16,17,npc_dota_hero_storm_spirit,int,Ranged,"[Carry, Escape, Nuker, Initiator, Disabler]",/apps/dota2/images/dota_react/heroes/storm_spi...,/apps/dota2/images/dota_react/heroes/icons/sto...,120,0.50,75,0.00,1,25,24,34,21,22,23,2.0,2.6,3.9,480,1100,1.6,115,0.500,285,0.8,True,2,1800,800,Storm Spirit,10813,5351,28785,14271,44260,22035,50759,25240,43151,21671,28332,14251,17157,8575,9925,5008,117562,"[22007, 21786, 18296, 16865, 16513, 18059, 4036]",59335,"[11028, 10943, 9242, 8485, 8442, 9155, 2040]",185,112,280,251155,"[47283, 47174, 37929, 36950, 34570, 37632, 9617]",125274,"[23802, 23191, 18910, 18520, 17207, 18800, 4844]"
17,18,npc_dota_hero_sven,str,Melee,"[Carry, Disabler, Initiator, Durable, Nuker]",/apps/dota2/images/dota_react/heroes/sven.png?,/apps/dota2/images/dota_react/heroes/icons/sve...,120,0.75,75,0.00,-1,25,37,39,25,21,16,3.2,2.2,1.5,150,0,1.9,110,0.400,325,NaN,True,2,1800,800,Sven,10004,4612,24362,10955,33184,15275,32890,15345,26370,12297,16576,7860,9438,4459,5714,2637,77402,"[14903, 14808, 11972, 11229, 10731, 11093, 2666]",35890,"[6913, 6922, 5637, 5168, 4974, 5045, 1231]",180,92,76,178230,"[34459, 34206, 28248, 26309, 24448, 24047, 6513]",82723,"[15978, 15937, 13111, 12221, 11259, 11213, 3004]"
18,19,npc_dota_hero_tiny,str,Melee,"[Carry, Nuker, Pusher, Initiator, Durable, Dis...",/apps/dota2/images/dota_react/heroes/tiny.png?,/apps/dota2/images/dota_react/heroes/icons/tin...,120,2.00,75,0.00,0,25,31,37,30,0,17,4.0,0.0,2.2,150,900,1.7,90,0.400,275,NaN,True,2,1800,800,Tiny,13404,6550,35315,16823,49457,23374,54435,25691,45528,21600,29900,14330,18493,8833,11966,5720,128835,"[24466, 23885, 20116, 19067, 18173, 19065, 4063]",61157,"[11588, 11185, 9586, 9073, 8633, 9172, 1920]",297,134,215,282538,"[52036, 52755, 44876, 42617, 39239, 40694, 10321]",134649,"[24824, 24956, 21490, 20321, 18520, 19537, 5001]"
19,20,npc_dota_hero_vengefulspirit,all,Ranged,"[Support, Initiator, Disabler, Nuker, Escape]",/apps/dota2/images/dota_react/heroes/vengefuls...,/apps/dota2/images/dota_react/heroes/icons/ven...,120,0.25,75,0.00,0,25,9,15,20,21,19,2.1,2.1,1.2,400,1500,1.7,110,0.330,295,NaN,True,2,1800,800,Vengeful Spirit,10631,5333,34013,17254,54770,28059,64117,33187,55133,28459,36516,19181,22431,11575,12003,6254,123043,"[23675, 23347, 19146, 18475, 16973, 17673, 3754]",66000,"[12692, 12493, 10315, 9950, 9119, 9446, 1985]",388,189,207,308467,"[57951, 57793, 48838, 46567, 42949, 43997, 10372]",158889,"[29914, 29730, 25215, 24014, 21971, 22704, 5341]"
20,21,npc_dota_hero_windrunner,all,Ranged,"[Carry, Support, Disabler, Escape, Nuker]",/apps/dota2/images/dota_react/heroes/windrunne...,/apps/dota2/images/dota_react/heroes/icons/win...,120,0.25,75,0.25,0,25,7,13,18,17,21,2.0,1.4,2.4,600,1250,1.5,90,0.400,290,0.8,True,2,1800,800,Windranger,21628,10226,61235,29202,93066,44843,107837,52785,93671,46594,62416,31489,39399,19838,24693,12541,216695,"[38242, 38443, 31539, 30106, 30494, 38790, 9081]",105349,"[18420, 18618, 15302, 14224, 14870, 19447, 4468]",467,247,872,538925,"[93778, 95184, 78624, 75152, 75547, 96826, 23814]",264264,"[45759, 46176, 38072, 36665, 37202, 48461, 11929]"
21,22,npc_dota_hero_zuus,int,Ranged,"[Nuker, Carry]",/apps/dota2/images/dota_react/heroes/zuus.png?,/apps/dota2/images/dota_react/heroes/icons/zuu...,120,0.25,75,0.00,2,25,33,41,19,11,22,2.1,1.2,3.3,380,1100,1.7,100,0.350,315,NaN,True,2,1800,800,Zeus,22916,11432,63191,32481,92007,47316,95058,48337,74679,38222,44623,22638,25700,12868,12420,6177,276498,"[50994, 51195, 43106, 41368, 39069, 41418, 9348]",137919,"[25279, 25595, 21349, 20808, 19572, 20572, 4744]",234,95,157,471823,"[85472, 88019, 73958, 70763, 66300, 69065, 18246]",239887,"[43171, 44933, 37542, 35915, 33746, 35237, 9343]"
22,23,npc_dota_hero_kunkka,str,Melee,"[Carry, Support, Disabler, Initiator, Durable,...",/apps/dota2/images/dota_react/heroes/kunkka.png?,/apps/dota2/images/dota_react/heroes/icons/kun...,120,0.75,75,0.00,2,25,30,36,24,14,18,3.6,1.6,1.8,150,900,1.7,100,0.400,315,NaN,True,2,1800,800,Kunkka,7118,3516,20272,10121,30420,15481,34727,17981,30030,15530,19170,9905,11653,6097,6301,3224,65050,"[11984, 11792, 9703, 9186, 9236, 10725, 2424]",32005,"[5837, 5865, 4676, 4582, 4515, 5347, 1183]",161,74,142,178793,"[29748, 31125, 26623, 25287, 25409, 31989, 8612]",91482,"[15211, 15868, 13635, 12872, 12928, 16497, 4471]"
23,25,npc_dota_hero_lina,int,Ranged,"[Support, Carry, Nuker, Disabler]",/apps/dota2/images/dota_react/heroes/lina.png?,/apps/dota2/images/dota_react/heroes/icons/lin...,120,0.25,75,0.00,0,25,21,29,20,23,30,2.4,2.4,3.8,670,1000,1.6,100,0.650,290,NaN,True,2,1800,800,Lina,26492,12275,69477,32647,102379,48689,113905,54649,94609,45903,62611,30574,38636,19064,24536,12295,236811,"[44817, 44657, 37380, 34469, 32820, 35155, 7513]",111394,"[21258, 21025, 17521, 16200, 15343, 16508, 3539]",414,204,1030,579348,"[107612, 109467, 91271, 86498, 79415, 83950, 2...",278404,"[51911, 52555, 43721, 41536, 38051, 40477, 10153]"
24,26,npc_dota_hero_lion,int,Ranged,"[Support, Disabler, Nuker, Initiator]",/apps/dota2/images/dota_react/heroes/lion.png?,/apps/dota2/images/dota_react/heroes/icons/lio...,120,0.50,75,0.00,0,25,29,35,18,15,20,2.4,1.7,3.5,600,900,1.7,115,0.430,290,NaN,True,2,1800,800,Lion,33046,16484,102369,50436,150690,74125,156995,77286,118648,58432,68606,33502,36474,17827,14437,7046,305731,"[55871, 57234, 48052, 45830, 43148, 45511, 10085]",146346,"[26788, 27338, 23165, 21727, 20750, 21702, 4876]",382,203,96,736816,"[131972, 136447, 116055, 110401, 104602, 10898...",362973,"[64877, 67013, 57199, 54179, 51885, 53797, 14023]"
25,27,npc_dota_hero_shadow_shaman,int,Ranged,"[Support, Pusher, Disabler, Nuker, Initiator]",/apps/dota2/images/dota_react/heroes/shadow_sh...,/apps/dota2/images/dota_react/heroes/icons/sha...,120,1.00,75,0.00,3,25,40,47,20,16,25,2.3,1.6,3.5,400,900,1.7,90,0.300,285,NaN,True,2,1800,800,Shadow Shaman,24683,13089,66946,35419,86932,45488,84933,44287,59892,31219,33998,17724,17905,9278,7044,3700,173744,"[31498, 32648, 27559, 26152, 24713, 25439, 5735]",91436,"[16492, 17225, 14499, 13769, 12946, 13444, 3061]",187,89,80,418707,"[74809, 77616, 66121, 63284, 59680, 60971, 16226]",219426,"[39330, 40589, 34830, 33125, 31163, 31903, 8486]"
26,28,npc_dota_hero_slardar,str,Melee,"[Carry, Durable, Initiator, Disabler, Escape]",/apps/dota2/images/dota_react/heroes/slardar.png?,/apps/dota2/images/dota_react/heroes/icons/sla...,120,0.50,75,0.00,3,25,30,38,21,17,15,3.6,2.1,1.5,150,0,1.7,100,0.360,300,NaN,True,0,1800,800,Slardar,14196,7031,37645,18417,50866,24791,50509,24619,37428,18491,21196,10460,11686,5721,5854,2906,106575,"[19246, 19578, 16222, 15976, 15461, 16362, 3730]",55174,"[9876, 10086, 8431, 8253, 8104, 8478, 1946]",194,86,124,258998,"[46293, 47308, 40356, 38698, 37075, 39163, 10105]",127257,"[22879, 23172, 19732, 19064, 18236, 19239, 4935]"
27,29,npc_dota_hero_tidehunter,str,Melee,"[Initiator, Durable, Disabler, Nuker, Carry]",/apps/dota2/images/dota_react/heroes/tidehunte...,/apps/dota2/images/dota_react/heroes/icons/tid...,120,0.25,75,0.50,0,25,25,31,27,15,20,3.6,1.5,1.7,150,900,1.7,100,0.600,300,NaN,True,2,1800,800,Tidehunter,8880,4398,25971,12703,38875,19026,40433,19635,30264,14635,16574,8020,8346,3915,3329,1548,82819,"[15912, 15919, 12753, 12060, 11446, 11983, 2746]",42873,"[8179, 8276, 6638, 6248, 5919, 6213, 1400]",91,45,26,188643,"[35400, 35963, 29624, 27988, 26128, 26351, 7189]",91769,"[17250, 17452, 14276, 13605, 12900, 12799, 3487]"
28,30,npc_dota_hero_witch_doctor,int,Ranged,"[Support, Nuker, Disabler]",/apps/dota2/images/dota_react/heroes/witch_doc...,/apps/dota2/images/dota_react/heroes/icons/wit...,120,0.25,75,0.00,0,25,26,36,20,13,22,2.1,1.4,3.1,550,1200,1.7,100,0.400,300,NaN,True,2,1800,800,Witch Doctor,27061,14600,84559,45262,123181,65844,123157,64551,89101,46040,48549,24560,25028,12362,9008,4399,253846,"[45809, 47113, 39656, 38394, 36434, 38039, 8401]",137419,"[24744, 25723, 21351, 20777, 19740, 20643, 4441]",246,108,117,567079,"[102089, 105703, 89159, 85536, 80460, 83422, 2...",297377,"[53334, 55623, 46770, 44630, 42369, 43796, 10855]"
29,31,npc_dota_hero_lich,int,Ranged,"[Support, Nuker]",/apps/dota2/images/dota_react/heroes/lich.png?,/apps/dota2/images/dota_react/heroes/icons/lic...,120,0.50,75,0.75,-1,25,24,33,20,17,26,2.1,2.0,3.8,550,900,1.7,100,0.460,290,0.7,True,2,1800,800,Lich,14702,7972,41516,22457,60612,32582,67958,36624,56470,30113,35832,18903,21588,11350,9563,4856,137126,"[25122, 25651, 21408, 20778, 19319, 20272, 4576]",77513,"[14204, 14506, 12198, 11713, 10923, 11420, 2549]",225,107,91,334961,"[60581, 62022, 52996, 50790, 47376, 48876, 12320]",179161,"[32365, 33284, 28484, 27031, 25241, 26160, 6596]"
30,32,npc_dota_hero_riki,agi,Melee,"[Carry, Escape, Disabler]",/apps/dota2/images/dota_react/heroes/riki.png?,/apps/dota2/images/dota_react/heroes/icons/rik...,120,2.50,75,0.00,0,25,22,26,18,30,14,2.0,2.4,1.3,150,900,1.7,90,0.300,315,NaN,True,2,1800,800,Riki,14905,7890,35125,18469,41407,21801,35632,18766,24103,12560,13074,6794,7162,3661,3740,1808,126087,"[22748, 22925, 19621, 19021, 18489, 18995, 4288]",65087,"[11808, 11816, 10082, 9915, 9451, 9805, 2210]",71,38,94,205768,"[34573, 36113, 31969, 32333, 31110, 31463, 8207]",107369,"[17953, 18986, 16772, 16773, 16283, 16290, 4312]"

In [5]:
df_hero_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 60 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 125 non-null    int64
 1   name               125 non-null    object
 2   primary_attr       125 non-null    object
 3   attack_type        125 non-null    object
 4   roles              125 non-null    object
 5   img                125 non-null    object
 6   icon               125 non-null    object
 7   base_health        125 non-null    int64
 8   base_health_regen  124 non-null    float64
 9   base_mana          125 non-null    int64
 10  base_mana_regen    125 non-null    float64
 11  base_armor         125 non-null    int64
 12  base_mr            125 non-null    int64
 13  base_attack_min    125 non-null    int64
 14  base_attack_max    125 non-null    int64
 15  base_str           125 non-null    int64
 16  base_agi           125 non-null    int64
 17  base_int           125 non-null    int64
 18  str_gain           125 non-null    float64
 19  agi_gain           125 non-null    float64
 20  int_gain           125 non-null    float64
 21  attack_range       125 non-null    int64
 22  projectile_speed   125 non-null    int64
 23  attack_rate        125 non-null    float64
 24  base_attack_time   125 non-null    int64
 25  attack_point       125 non-null    float64
 26  move_speed         125 non-null    int64
 27  turn_rate          43 non-null     float64
 28  cm_enabled         125 non-null    bool
 29  legs               125 non-null    int64
 30  day_vision         125 non-null    int64
 31  night_vision       125 non-null    int64
 32  localized_name     125 non-null    object
 33  1_pick             125 non-null    int64
 34  1_win              125 non-null    int64
 35  2_pick             125 non-null    int64
 36  2_win              125 non-null    int64
 37  3_pick             125 non-null    int64
 38  3_win              125 non-null    int64
 39  4_pick             125 non-null    int64
 40  4_win              125 non-null    int64
 41  5_pick             125 non-null    int64
 42  5_win              125 non-null    int64
 43  6_pick             125 non-null    int64
 44  6_win              125 non-null    int64
 45  7_pick             125 non-null    int64
 46  7_win              125 non-null    int64
 47  8_pick             125 non-null    int64
 48  8_win              125 non-null    int64
 49  turbo_picks        125 non-null    int64
 50  turbo_picks_trend  125 non-null    object
 51  turbo_wins         125 non-null    int64
 52  turbo_wins_trend   125 non-null    object
 53  pro_pick           125 non-null    int64
 54  pro_win            125 non-null    int64
 55  pro_ban            125 non-null    int64
 56  pub_pick           125 non-null    int64
 57  pub_pick_trend     125 non-null    object
 58  pub_win            125 non-null    int64
 59  pub_win_trend      125 non-null    object
dtypes: bool(1), float64(8), int64(40), object(11)
memory usage: 57.9+ KB

In [6]:
df_hero_stats.isnull().sum()

id                    0
name                  0
primary_attr          0
attack_type           0
roles                 0
img                   0
icon                  0
base_health           0
base_health_regen     1
base_mana             0
base_mana_regen       0
base_armor            0
base_mr               0
base_attack_min       0
base_attack_max       0
base_str              0
base_agi              0
base_int              0
str_gain              0
agi_gain              0
int_gain              0
attack_range          0
projectile_speed      0
attack_rate           0
base_attack_time      0
attack_point          0
move_speed            0
turn_rate            82
cm_enabled            0
legs                  0
day_vision            0
night_vision          0
localized_name        0
1_pick                0
1_win                 0
2_pick                0
2_win                 0
3_pick                0
3_win                 0
4_pick                0
4_win                 0
5_pick                0
5_win                 0
6_pick                0
6_win                 0
7_pick                0
7_win                 0
8_pick                0
8_win                 0
turbo_picks           0
turbo_picks_trend     0
turbo_wins            0
turbo_wins_trend      0
pro_pick              0
pro_win               0
pro_ban               0
pub_pick              0
pub_pick_trend        0
pub_win               0
pub_win_trend         0
dtype: int64

## Columns of interests
1. id
2. localized_name
3. pro_ban
4. pro_pick
5. pro_win
6. 8_win
7. 8_pick

*8_win/8_pick shows win/pick rate of this hero for immortal and above skill level, which is the average skill level of most competitive players*

In [7]:
HERO_COLUMNS = ['id','localized_name','pro_ban','pro_pick','pro_win','8_win','8_pick']
df_hero_final = df_hero_stats[HERO_COLUMNS]

In [10]:
from postgresql import create_records

# Storing hero stats to postgres
create_records(df_hero_final,'hero_stats',True)

## 2. Pro Players

In [15]:
df_pro_players

,account_id,steamid,avatar,avatarmedium,avatarfull,profileurl,personaname,last_login,full_history_time,cheese,fh_unavailable,loccountrycode,last_match_time,plus,name,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,1296625,76561197961562353,https://avatars.steamstatic.com/4a666edd6d1582...,https://avatars.steamstatic.com/4a666edd6d1582...,https://avatars.steamstatic.com/4a666edd6d1582...,https://steamcommunity.com/id/Newsham/,Newsham,2023-10-21T21:51:11.911Z,2024-08-01T14:28:04.672Z,0.0,False,US,2024-08-31T06:50:25.000Z,True,Newsham,,2,8944221,Fart Studios,FRT,True,True,None
1,10366616,76561197970632344,https://avatars.steamstatic.com/c19fed8e57530f...,https://avatars.steamstatic.com/c19fed8e57530f...,https://avatars.steamstatic.com/c19fed8e57530f...,https://steamcommunity.com/profiles/7656119797...,Sneyking,2024-06-15T16:29:32.493Z,2024-08-27T12:37:17.019Z,0.0,True,None,2024-08-25T18:49:28.000Z,True,Sneyking,us,2,9247354,Team Falcons,FLCN,True,True,None
2,16497807,76561197976763535,https://avatars.steamstatic.com/a0aca11d96d24e...,https://avatars.steamstatic.com/a0aca11d96d24e...,https://avatars.steamstatic.com/a0aca11d96d24e...,https://steamcommunity.com/id/to_Ofu/,tOfu,2020-12-05T02:26:53.827Z,2024-08-29T19:31:57.116Z,0.0,True,DE,2024-08-22T18:29:02.000Z,True,tOfu,de,2,8599101,Gaimin Gladiators,GG,True,True,None
3,18180970,76561197978446698,https://avatars.steamstatic.com/1e27bcd82490cb...,https://avatars.steamstatic.com/1e27bcd82490cb...,https://avatars.steamstatic.com/1e27bcd82490cb...,https://steamcommunity.com/profiles/7656119797...,skruva den som pabbe,2018-12-09T23:16:04.851Z,2024-07-10T12:04:20.524Z,0.0,True,None,2024-07-23T17:04:27.000Z,False,Handsken,se,2,9368468,Rest Farmers,zzz,True,True,None
4,25907144,76561197986172872,https://avatars.steamstatic.com/f93ff4cee87a07...,https://avatars.steamstatic.com/f93ff4cee87a07...,https://avatars.steamstatic.com/f93ff4cee87a07...,https://steamcommunity.com/profiles/7656119798...,Cr1t-,2019-01-01T20:42:28.178Z,2024-08-27T11:47:25.081Z,0.0,False,None,2024-08-31T19:59:20.000Z,True,Cr1t-,dk,2,9247354,Team Falcons,FLCN,True,True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,1657135701,76561199617401429,https://avatars.steamstatic.com/737ac4f0d404a2...,https://avatars.steamstatic.com/737ac4f0d404a2...,https://avatars.steamstatic.com/737ac4f0d404a2...,https://steamcommunity.com/id/w0me/,血腥武士刀之路,None,2024-08-25T23:50:15.777Z,0.0,False,None,2024-08-31T20:46:05.000Z,True,nesfeer,,0,8376696,One Move,Move,True,True,None
463,1673586483,76561199633852211,https://avatars.steamstatic.com/424652c6a8ab86...,https://avatars.steamstatic.com/424652c6a8ab86...,https://avatars.steamstatic.com/424652c6a8ab86...,https://steamcommunity.com/profiles/7656119963...,Zone,None,2024-03-14T11:11:35.270Z,0.0,False,None,2024-09-01T01:59:34.000Z,True,wonderk1d^^<,,0,7119077,Hokori,Hokori,True,True,None
464,1675675311,76561199635941039,https://avatars.steamstatic.com/fc53c46ffd3629...,https://avatars.steamstatic.com/fc53c46ffd3629...,https://avatars.steamstatic.com/fc53c46ffd3629...,https://steamcommunity.com/profiles/7656119963...,uurlaj bn bi.,None,2024-06-20T06:50:26.274Z,0.0,True,None,2024-06-25T11:05:13.000Z,False,Ikigai鷹,,0,9005019,IHC,IHC,True,True,None
465,1682179459,76561199642445187,https://avatars.steamstatic.com/864a37cd71bdbd...,https://avatars.steamstatic.com/864a37cd71bdbd...,https://avatars.steamstatic.com/864a37cd71bdbd...,https://steamcommunity.com/id/meditatsiavkolodce/,Медитация в колодце,None,2024-08-11T01:21:16.276Z,0.0,True,None,2024-08-25T09:00:16.000Z,False,Wein,,0,8376696,One Move,Move,True,True,None
466,1690624451,None,None,None,None,None,None,None,None,NaN,None,None,None,None,Danial,,0,8538804,Rectify,Rekt,True,True,None

In [16]:
df_pro_players.isnull().sum()

account_id             0
steamid                1
avatar                 1
avatarmedium           1
avatarfull             1
profileurl             1
personaname            1
last_login           209
full_history_time      3
cheese                 1
fh_unavailable         3
loccountrycode       141
last_match_time        1
plus                   1
name                   0
country_code           0
fantasy_role           0
team_id                0
team_name              0
team_tag               0
is_locked              0
is_pro                 0
locked_until         467
dtype: int64

## Columns of interests from pro_players

1. account_id
2. name (Verified player's name)
3. last_match_time (datetime) -> Date and time of last request to refresh player's match history
4. fantasy_role (Player's ingame role)
5. team_id (player's team identifier)

In [17]:
## Creating the Pro_players table 

PLAYERS_COLUMNS = ['account_id','name','fantasy_role','team_id','last_match_time']
df_pro_players = df_pro_players[PLAYERS_COLUMNS].copy()
df_pro_players

     account_id          name  fantasy_role  team_id           last_match_time
0       1296625       Newsham             2  8944221  2024-08-31T06:50:25.000Z
1      10366616      Sneyking             2  9247354  2024-08-25T18:49:28.000Z
2      16497807          tOfu             2  8599101  2024-08-22T18:29:02.000Z
3      18180970      Handsken             2  9368468  2024-07-23T17:04:27.000Z
4      25907144         Cr1t-             2  9247354  2024-08-31T19:59:20.000Z
..          ...           ...           ...      ...                       ...
462  1657135701       nesfeer             0  8376696  2024-08-31T20:46:05.000Z
463  1673586483  wonderk1d^^<             0  7119077  2024-09-01T01:59:34.000Z
464  1675675311       Ikigai鷹             0  9005019  2024-06-25T11:05:13.000Z
465  1682179459          Wein             0  8376696  2024-08-25T09:00:16.000Z
466  1690624451        Danial             0  8538804                      None

[467 rows x 5 columns]

### Limitations

The number of competitive players stored in this database is incomplete

## Pro Matches Endpoint

In [18]:
df_pro_matches

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win,version
0,7923232708,1392,1725157286,9466547,Team Echo,9466548,IronClaw,17021,Culling Blade League,902616,1,34,48,False,21.0
1,7923207205,1505,1725154993,9466548,IronClaw,9466547,Team Echo,17021,Culling Blade League,902616,1,42,39,True,21.0
2,7923203847,2063,1725154720,8850016,FLYING FORTUNE,8849850,HELLBEAR HEROES,16635,Dota 2 Space League,902606,2,22,29,True,21.0
3,7923169949,2484,1725151404,8849850,HELLBEAR HEROES,8850016,FLYING FORTUNE,16635,Dota 2 Space League,902606,2,41,54,False,21.0
4,7923140944,1977,1725148343,8850016,FLYING FORTUNE,8849850,HELLBEAR HEROES,16635,Dota 2 Space League,902606,2,27,35,False,21.0
5,7923111135,1837,1725145777,8849850,HELLBEAR HEROES,8850016,FLYING FORTUNE,16635,Dota 2 Space League,902606,2,38,22,True,21.0
6,7923076640,1215,1725143179,8849990,REAL ECLIPSE,8849850,HELLBEAR HEROES,16635,Dota 2 Space League,902588,1,9,38,False,21.0
7,7923037228,1648,1725140668,8849850,HELLBEAR HEROES,8849990,REAL ECLIPSE,16635,Dota 2 Space League,902588,1,12,29,False,21.0
8,7923029379,1298,1725140404,9499095,Legacy,9450071,Fusion Esports,17074,Bitel True Fighters 2024,902569,1,26,12,True,21.0
9,7922967873,2697,1725137019,8849990,REAL ECLIPSE,8849850,HELLBEAR HEROES,16635,Dota 2 Space League,902588,1,32,53,False,21.0
10,7922941804,2841,1725135730,9499095,Legacy,9450071,Fusion Esports,17074,Bitel True Fighters 2024,902569,1,30,29,True,21.0
11,7922904036,1884,1725134037,8970060,Moonwalkers,8850016,FLYING FORTUNE,16635,Dota 2 Space League,902567,1,29,34,False,21.0
12,7922843279,2168,1725131803,9499095,Legacy,9450071,Fusion Esports,17074,Bitel True Fighters 2024,902569,1,14,34,False,21.0
13,7922841114,1602,1725131327,8850016,FLYING FORTUNE,8970060,Moonwalkers,16635,Dota 2 Space League,902567,1,37,23,True,21.0
14,7922812260,1418,1725130113,9493584,Eye Gaming,9338738,Shinigami Gaming,15901,Ultras Dota Pro League 2023-24,902543,1,52,18,True,21.0
15,7922738012,1536,1725127145,8855399,Kuma no Seishin,8804035,None,16251,Party To Play league,902545,0,15,45,False,21.0
16,7922731710,1439,1725126800,9338738,Shinigami Gaming,9493584,Eye Gaming,15901,Ultras Dota Pro League 2023-24,902543,1,16,49,False,21.0
17,7922721811,2215,1725126540,9432799,Cuyes e-Sports,8375259,Infinity,17074,Bitel True Fighters 2024,902485,1,33,17,True,21.0
18,7922643558,2249,1725123339,8855399,Kuma no Seishin,9488831,RUSSIAN FISHING,16251,Party To Play league,902521,0,54,37,True,21.0
19,7922614316,2786,1725122102,9432799,Cuyes e-Sports,8375259,Infinity,17074,Bitel True Fighters 2024,902485,1,34,41,False,21.0
20,7922518970,2196,1725118540,9482251,Eye Gaming,9440022,Elite Eclipse,15901,Ultras Dota Pro League 2023-24,902493,1,32,54,False,21.0
21,7922498330,3480,1725117779,9488831,RUSSIAN FISHING,9433856,xdxdxd,16251,Party To Play league,902488,0,56,38,True,21.0
22,7922489003,1934,1725117443,8563565,PUFF,9132931,B8,16251,Party To Play league,902486,0,25,15,True,21.0
23,7922483571,2646,1725117247,9432799,Cuyes e-Sports,8375259,Infinity,17074,Bitel True Fighters 2024,902485,1,38,19,True,21.0
24,7922476571,2415,1725116998,9500221,Пещерные недомерки,8804035,None,16251,Party To Play league,902483,0,44,43,False,21.0
25,7922469337,2522,1725116798,9119898,Солевые TEAM,8855399,Kuma no Seishin,16251,Party To Play league,902480,0,21,40,False,21.0
26,7922347716,2092,1725112359,9440022,Elite Eclipse,9473226,EYE GAMING,15901,Ultras Dota Pro League 2023-24,902456,1,41,22,True,21.0
27,7922256306,1515,1725108842,8831040,Ghost Sheep,9344594,Dominion,15901,Ultras Dota Pro League 2023-24,902430,1,50,15,True,21.0
28,7922201066,1751,1725106580,9472684,None,9098294,Carstensz Esports,16968,The Flame League,902409,1,49,18,True,21.0
29,7922184858,1546,1725106111,9344594,Dominion,8831040,Ghost Sheep,15901,Ultras Dota Pro League 2023-24,902430,1,11,51,False,21.0
30,7922102743,1273,1725102064,9482722,Elite Eclipse,9512146,Prodigy of God,15901,Ultras Dota Pro League 2023-24,902413,1,12,34,False,21.0
31,7922083713,2194,1725101282,9472684,None,9098294,Carstensz Esports,16968,The Flame League,902409,1,40,26,True,21.0
32,7922028772,1115,1725098255,9512487,None,9461007,Evil Rabbit,17059,Phoenix League,902397,1,29,8,True,21.0
33,7922008753,2794,1725097181,9476660,Prodigy of God,9482722,Elite Eclipse,15901,Ultras Dota Pro League 2023-24,902401,1,37,40,True,21.0
34,7921967399,1725,1725095132,9512487,None,9461007,Evil Rabbit,17059,Phoenix League,902397,1,10,26,False,21.0
35,7921943003,2199,1725093734,8629014,Dragon Blood,8629005,Flawless Goblins,16059,Destiny League,902377,1,52,37,True,21.0
36,7921936932,2679,1725093395,9481964,Elite Eclipse,9512146,Prodigy of God,15901,Ultras Dota Pro League 2023-24,902391,1,41,39,True,21.0
37,7921935672,1526,1725093277,9018528,Crew X,8893825,Lucky Bulldogs,16312,Ancients League,902384,1,23,28,False,21.0
38,7921913962,1330,1725092101,9018664,Team Bright,9512487,None,17059,Phoenix League,902375,1,20,4,True,21.0
39,7921906160,1555,1725091739,9425660,Shadow Avengers,8629318,Mad Monkeys,16059,Destiny League,902386,1,38,26,True,21.0
40,7921900583,1766,1725091464,8629005,Flawless Goblins,8629014,Dragon Blood,16059,Destiny League,902377,1,20,36,False,21.0
41,7921894070,1888,1725090895,8893825,Lucky Bulldogs,9018528,Crew X,16312,Ancients League,902384,1,21,26,True,21.0
42,7921875266,4182,1725089782,9254408,The Immortal,9098294,Carstensz Esports,16968,The Flame League,902369,1,47,67,False,21.0
43,7921865299,1584,1725089575,8629318,Mad Monkeys,9425660,Shadow Avengers,16059,Destiny League,902379,1,12,29,False,21.0
44,7921859768,1585,1725089027,8629014,Dragon Blood,8629005,Flawless Goblins,16059,Destiny League,902377,1,15,31,False,21.0
45,7921852539,1592,1725088375,9493584,Eye Gaming,9476660,Prodigy of God,15901,Ultras Dota Pro League 2023-24,900385,1,18,46,False,21.0
46,7921844989,1885,1725088279,9018664,Team Bright,9512487,None,17059,Phoenix League,902375,1,39,22,True,NaN
47,7921834209,1633,1725087194,9332046,Dominatrix,9330492,Iconic,16312,Ancients League,902368,1,18,32,False,21.0
48,7921829031,1125,1725086896,9425656,LSG,2443375,Foxy gaming,16059,Destiny League,902367,1,12,39,False,21.0
49,7921809336,2093,1725085507,8629315,Wiser Warriors,9426115,Dark Rebellion,16059,Destiny League,902364,1,33,29,False,21.0
50,7921801872,2834,1725084932,9254408,The Immortal,9098294,Carstensz Esports,16968,The Flame League,902369,1,22,41,False,21.0
51,7921798182,2012,1725084672,8944230,Yangon Galacticos,9409659,spiky gaming,17059,Phoenix League,902360,1,31,16,True,21.0
52,7921796027,1897,1725084521,9330492,Iconic,9332046,Dominatrix,16312,Ancients League,902368,1,39,32,True,21.0
53,7921793427,1676,1725084361,9425656,LSG,2443375,Foxy gaming,16059,Destiny League,902367,1,25,42,False,21.0
54,7921789539,1658,1725084092,9360936,Prodigy Of God,9493584,Eye Gaming,15901,Ultras Dota Pro League 2023-24,902366,1,41,10,True,21.0
55,7921770855,1781,1725082926,9426115,Dark Rebellion,8629315,Wiser Warriors,16059,Destiny League,902364,1,32,19,True,21.0
56,7921768595,1240,1725082451,8893840,Big Bang Gaming,8893837,Parallel eSports,16312,Ancients League,902342,1,31,4,True,21.0
57,7921748820,2050,1725081128,8944230,Yangon Galacticos,9409659,spiky gaming,17059,Phoenix League,902360,1,19,22,False,21.0
58,7921743296,1817,1725081214,8629014,Dragon Blood,8629324,Swift Knights,16059,Destiny League,902337,1,19,32,False,21.0
59,7921737768,1664,1725080054,8629318,Mad Monkeys,8629317,Bright Crusaders,16059,Destiny League,902344,1,26,33,False,21.0
60,7921737511,1786,1725079977,9466208,None,9472684,None,16968,The Flame League,902338,1,23,57,False,21.0
61,7921730661,2332,1725079400,8893837,Parallel eSports,8893840,Big Bang Gaming,16312,Ancients League,902342,1,25,29,False,21.0
62,7921716727,1562,1725078418,8629324,Swift Knights,8629014,Dragon Blood,16059,Destiny League,902337,1,42,21,True,21.0
63,7921705725,2091,1725077422,8629317,Bright Crusaders,8629318,Mad Monkeys,16059,Destiny League,902344,1,32,28,True,21.0
64,7921704155,1573,1725077153,8893840,Big Bang Gaming,8893837,Parallel eSports,16312,Ancients League,902342,1,17,24,False,21.0
65,7921691763,1715,1725076129,9472684,None,9466208,None,16968,The Flame League,902338,1,42,18,True,21.0
66,7921680524,2143,1725075187,8629014,Dragon Blood,8629324,Swift Knights,16059,Destiny League,902337,1,35,32,True,21.0
67,7921604624,1766,1725068488,8849837,FALL VICTIMS,8849990,REAL ECLIPSE,16635,Dota 2 Space League,902322,1,25,30,True,21.0
68,7921549566,1450,1725063007,8849837,FALL VICTIMS,8849990,REAL ECLIPSE,16635,Dota 2 Space League,902315,1,25,12,True,21.0
69,7921524632,1559,1725060680,8850016,FLYING FORTUNE,8957156,Silent killer,16635,Dota 2 Space League,902309,1,35,20,True,21.0
70,7921486102,1552,1725057592,8957156,Silent killer,8850016,FLYING FORTUNE,16635,Dota 2 Space League,902309,1,20,29,False,21.0
71,7921455962,3083,1725055447,9081369,Infamous Gaming,9432799,Cuyes e-Sports,17074,Bitel True Fighters 2024,902298,1,33,39,False,21.0
72,7921442174,1874,1725054696,8849833,VERTEX PACK,8970060,Moonwalkers,16635,Dota 2 Space League,902295,1,19,31,False,21.0
73,7921399876,1833,1725052201,8970060,Moonwalkers,8849833,VERTEX PACK,16635,Dota 2 Space League,902295,1,32,22,True,21.0
74,7921385379,2114,1725051602,9432799,Cuyes e-Sports,9081369,Infamous Gaming,17074,Bitel True Fighters 2024,902298,1,36,20,True,21.0
75,7921359084,1597,1725050092,8849833,VERTEX PACK,8970060,Moonwalkers,16635,Dota 2 Space League,902295,1,32,22,True,21.0
76,7921299634,1645,1725047331,8849850,HELLBEAR HEROES,8936613,Wild Dragon,16635,Dota 2 Space League,902286,1,11,22,False,21.0
77,7921284304,2494,1725047094,9302841,South Team,9081369,Infamous Gaming,17074,Bitel True Fighters 2024,902247,1,30,42,False,21.0
78,7921122651,2268,1725039576,9302841,South Team,9081369,Infamous Gaming,17074,Bitel True Fighters 2024,902247,1,16,36,False,21.0
79,7921106793,2055,1725038929,9498970,AVULUS,9255039,1w Team,17056,CCT Dota 2 Series 3,902208,2,23,14,True,21.0
80,7921050898,2550,1725036666,9395676,Shinigami gaming,9467112,Prodigy Of God,15901,Ultras Dota Pro League 2023-24,902215,1,31,45,False,21.0
81,7921025318,1872,1725035713,8629318,Mad Monkeys,8629315,Wiser Warriors,16059,Destiny League,902217,1,16,31,False,21.0
82,7921007329,2326,1725034958,9255039,1w Team,9498970,AVULUS,17056,CCT Dota 2 Series 3,902208,2,19,30,False,21.0
83,7920992510,1595,1725034389,9432799,Cuyes e-Sports,9499095,Legacy,17074,Bitel True Fighters 2024,902205,1,10,41,False,21.0
84,7920949384,1921,1725032786,8629315,Wiser Warriors,8629318,Mad Monkeys,16059,Destiny League,902217,1,27,15,True,21.0
85,7920908457,2514,1725031255,9467112,Prodigy Of God,9395676,Shinigami gaming,15901,Ultras Dota Pro League 2023-24,902215,1,52,37,True,21.0
86,7920893358,1384,1725030749,8629005,Flawless Goblins,2443375,Foxy gaming,16059,Destiny League,902191,1,16,37,False,21.0
87,7920892781,1541,1725030718,9498970,AVULUS,9255039,1w Team,17056,CCT Dota 2 Series 3,902208,2,15,6,True,21.0
88,7920874575,2426,1725030207,9499095,Legacy,9432799,Cuyes e-Sports,17074,Bitel True Fighters 2024,902205,1,36,13,True,21.0
89,7920823625,1911,1725028168,2443375,Foxy gaming,8629005,Flawless Goblins,16059,Destiny League,902191,1,37,26,True,21.0
90,7920798013,2303,1725027096,9383024,Prodigy Of God,9481763,Dominion,15901,Ultras Dota Pro League 2023-24,895310,1,34,47,False,21.0
91,7920777765,2549,1725026414,9255039,1w Team,9498970,AVULUS,17056,CCT Dota 2 Series 3,902184,1,29,16,True,21.0
92,7920760797,1568,1725025909,8629005,Flawless Goblins,2443375,Foxy gaming,16059,Destiny League,902191,1,26,22,True,21.0
93,7920745819,1209,1725023827,9480855,Dominion,9383024,Prodigy Of God,15901,Ultras Dota Pro League 2023-24,902190,1,33,4,True,21.0
94,7920728911,1729,1725023142,9498970,AVULUS,9255039,1w Team,17056,CCT Dota 2 Series 3,902184,1,8,23,False,21.0
95,7920696510,1564,1725021805,8629324,Swift Knights,8629317,Bright Crusaders,16059,Destiny League,902177,1,36,20,True,NaN
96,7920639676,1905,1725019246,8629317,Bright Crusaders,8629324,Swift Knights,16059,Destiny League,902177,1,25,42,False,21.0
97,7920629488,2234,1725018767,9088071,EYE Gaming,9504550,Prodigy of God,15901,Ultras Dota Pro League 2023-24,902168,1,43,29,True,21.0
98,7920559806,1565,1725015124,9330489,ThunderLab,9018528,Crew X,16312,Ancients League,902163,1,16,34,False,21.0
99,7920551265,2922,1725014643,9504550,Prodigy of God,9088071,EYE Gaming,15901,Ultras Dota Pro League 2023-24,902168,1,39,31,True,21.0

# Columns of interest

1. match_id
2. start_time
3. radiant_team_id
4. radiant_name
5. dire_team_id
6. dire_name
7. leagueid
8. league_name

# Limitations

Does not contain information such as hero picks and players' account_id. Is a good endpoint to extract the match_id of a list of pro_matches. Use match_ids to fetch the complete dataset from Steam's API

## Constants

In [19]:
heroes_constants = get_opendota_df('constants/heroes')
heroes_constants

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,...,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,119,120,121,123,126,128,129,131,135,136,137,138
id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,...,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,119,120,121,123,126,128,129,131,135,136,137,138
name,npc_dota_hero_antimage,npc_dota_hero_axe,npc_dota_hero_bane,npc_dota_hero_bloodseeker,npc_dota_hero_crystal_maiden,npc_dota_hero_drow_ranger,npc_dota_hero_earthshaker,npc_dota_hero_juggernaut,npc_dota_hero_mirana,npc_dota_hero_morphling,npc_dota_hero_nevermore,npc_dota_hero_phantom_lancer,npc_dota_hero_puck,npc_dota_hero_pudge,npc_dota_hero_razor,npc_dota_hero_sand_king,npc_dota_hero_storm_spirit,npc_dota_hero_sven,npc_dota_hero_tiny,npc_dota_hero_vengefulspirit,npc_dota_hero_windrunner,npc_dota_hero_zuus,npc_dota_hero_kunkka,npc_dota_hero_lina,npc_dota_hero_lion,npc_dota_hero_shadow_shaman,npc_dota_hero_slardar,npc_dota_hero_tidehunter,npc_dota_hero_witch_doctor,npc_dota_hero_lich,npc_dota_hero_riki,npc_dota_hero_enigma,npc_dota_hero_tinker,npc_dota_hero_sniper,npc_dota_hero_necrolyte,npc_dota_hero_warlock,npc_dota_hero_beastmaster,npc_dota_hero_queenofpain,npc_dota_hero_venomancer,npc_dota_hero_faceless_void,npc_dota_hero_skeleton_king,npc_dota_hero_death_prophet,npc_dota_hero_phantom_assassin,npc_dota_hero_pugna,npc_dota_hero_templar_assassin,npc_dota_hero_viper,npc_dota_hero_luna,npc_dota_hero_dragon_knight,npc_dota_hero_dazzle,npc_dota_hero_rattletrap,...,npc_dota_hero_lycan,npc_dota_hero_brewmaster,npc_dota_hero_shadow_demon,npc_dota_hero_lone_druid,npc_dota_hero_chaos_knight,npc_dota_hero_meepo,npc_dota_hero_treant,npc_dota_hero_ogre_magi,npc_dota_hero_undying,npc_dota_hero_rubick,npc_dota_hero_disruptor,npc_dota_hero_nyx_assassin,npc_dota_hero_naga_siren,npc_dota_hero_keeper_of_the_light,npc_dota_hero_wisp,npc_dota_hero_visage,npc_dota_hero_slark,npc_dota_hero_medusa,npc_dota_hero_troll_warlord,npc_dota_hero_centaur,npc_dota_hero_magnataur,npc_dota_hero_shredder,npc_dota_hero_bristleback,npc_dota_hero_tusk,npc_dota_hero_skywrath_mage,npc_dota_hero_abaddon,npc_dota_hero_elder_titan,npc_dota_hero_legion_commander,npc_dota_hero_techies,npc_dota_hero_ember_spirit,npc_dota_hero_earth_spirit,npc_dota_hero_abyssal_underlord,npc_dota_hero_terrorblade,npc_dota_hero_phoenix,npc_dota_hero_oracle,npc_dota_hero_winter_wyvern,npc_dota_hero_arc_warden,npc_dota_hero_monkey_king,npc_dota_hero_dark_willow,npc_dota_hero_pangolier,npc_dota_hero_grimstroke,npc_dota_hero_hoodwink,npc_dota_hero_void_spirit,npc_dota_hero_snapfire,npc_dota_hero_mars,npc_dota_hero_ringmaster,npc_dota_hero_dawnbreaker,npc_dota_hero_marci,npc_dota_hero_primal_beast,npc_dota_hero_muerta
primary_attr,agi,str,all,agi,int,agi,str,agi,all,agi,agi,agi,int,str,agi,all,int,str,str,all,all,int,str,int,int,int,str,str,int,int,agi,all,int,agi,int,int,all,int,all,agi,str,int,agi,int,agi,agi,agi,str,all,all,...,all,all,int,all,str,agi,str,str,str,int,int,all,agi,int,all,all,agi,agi,agi,str,all,str,str,str,int,all,str,str,all,agi,str,str,agi,all,int,all,agi,agi,all,all,int,agi,all,all,str,int,str,all,str,int
attack_type,Melee,Melee,Ranged,Melee,Ranged,Ranged,Melee,Melee,Ranged,Ranged,Ranged,Melee,Ranged,Melee,Ranged,Melee,Ranged,Melee,Melee,Ranged,Ranged,Ranged,Melee,Ranged,Ranged,Ranged,Melee,Melee,Ranged,Ranged,Melee,Ranged,Ranged,Ranged,Ranged,Ranged,Melee,Ranged,Ranged,Melee,Melee,Ranged,Melee,Ranged,Ranged,Ranged,Ranged,Melee,Ranged,Melee,...,Melee,Melee,Ranged,Ranged,Melee,Melee,Melee,Melee,Melee,Ranged,Ranged,Melee,Melee,Ranged,Ranged,Ranged,Melee,Ranged,Ranged,Melee,Melee,Melee,Melee,Melee,Ranged,Melee,Melee,Melee,Ranged,Melee,Melee,Melee,Melee,Ranged,Ranged,Ranged,Ranged,Melee,Ranged,Melee,Ranged,Ranged,Melee,Ranged,Melee,Ranged,Melee,Melee,Melee,Ranged
roles,"[Carry, Escape, Nuker]","[Initiator, Durable, Disabler, Carry]","[Support, Disabler, Nuker, Durable]","[Carry, Disabler, Nuker, Initiator]","[Support, Disabler, Nuker]","[Carry, Disabler, Pusher]","[Support, Initiator, Disabler, Nuker]","[Carry, Pusher, Escape]","[Carry, Support, Escape, Nuker, Disabler]","[Carry, Escape, Durable, Nuker, Disabler]","[Carry, Nuker]","[Carry, Escape, Pusher, Nuker]","[Initiator, Disabler, Escape, Nuker]","[Disabler, Initiator, Durable, Nuker]","[Carry, Durable, Nuker, Pusher]","[Initiator, Disabler, Support, Nuker, Escape]","[Carry, Escape, Nuker, Initiator, Disabler]","[Carry, Disabler, Initiator, Durable, Nuker]","[Carry, Nuker, Pusher, Initiator, Durable, Dis...","[Support, Initiator, Disabler, Nuker, Escape]","[Carry, Support, Disabler, Escape, Nuker]","[Nuker, Carry]","[Carry, Support, Disabler, Initiator, Durable,...","[Support, Carry, Nuker, Disabler]","[Support, Disabler, Nuker, Initiator]","[Support, Pusher, Disabler, Nuker, Initiator]","[Carry, Durable, Initiator, Disabler, Escape]","[Initiator, Durable, Disabler, Nuker, Carry]","[Support, Nuker, Disabler]","[Support, Nuker]","[Carry, Escape, Disabler]","[Disabler, Initiator, Pusher]","[Carry, Nuker, Pusher]","[Carry, Nuker]","[Carry, Nuker, Durable, Disabler]","[Support, Initiator, Disabler]","[Initiator, Disabler, Durable, Nuker]","[Carry, Nuker, Escape]","[Support, Nuker, Initiator, Pusher, Disabler]","[Carry, Initiator, Disabler, Escape, Durable]","[Carry, Support, Durable, Disabler, Initiator]","[Carry, Pusher, Nuker, Disabler]","[Carry, Escape]","[Nuker, Pusher]","[Carry, Escape]","[Carry, Durable, Initiator, Disabler]","[Carry, Nuker, Pusher]","[Carry, Pusher, Durable, Disabler, Initiator, ...","[Support, Nuker, Disabler]","[Initiator, Disabler, Durable, Nuker]",...,"[Carry, Pusher, Durable, Escape]","[Carry, Initiator, Durable, Disabler, Nuker]","[Support, Disabler, Initiator, Nuker]","[Carry, Pusher, Durable]","[Carry, Disabler, Durable, Pusher, Initiator]","[Carry, Escape, Nuker, Disabler, Initiator, Pu...","[Support, Initiator, Durable, Disabler, Escape]","[Support, Nuker, Disabler, Durable, Initiator]","[Support, Durable, Disabler, Nuker]","[Support, Disabler, Nuker]","[Support, Disabler, Nuker, Initiator]","[Disabler, Nuker, Initiator, Escape]","[Carry, Support, Pusher, Disabler, Initiator, ...","[Support, Nuker, Disabler]","[Support, Escape, Nuker]","[Support, Nuker, Durable, Disabler, Pusher]","[Carry, Escape, Disabler, Nuker]","[Carry, Disabler, Durable]","[Carry, Pusher, Disabler, Durable]","[Durable, Initiator, Disabler, Nuker, Escape]","[Initiator, Disabler, Nuker, Escape]","[Nuker, Durable, Escape]","[Carry, Durable, Initiator, Nuker]","[Initiator, Disabler, Nuker]","[Support, Nuker, Disabler]","[Support, Carry, Durable]","[Initiator, Disabler, Nuker, Durable]","[Carry, Disabler, Initiator, Durable, Nuker]","[Nuker, Disabler]","[Carry, Escape, Nuker, Disabler, Initiator]","[Nuker, Escape, Disabler, Initiator, Durable]","[Support, Nuker, Disabler, Durable, Escape]","[Carry, Pusher, Nuker]","[Support, Nuker, Initiator, Escape, Disabler]","[Support, Nuker, Disabler, Escape]","[Support, Disabler, Nuker]","[Carry, Escape, Nuker]","[Carry, Escape, Disabler, Initiator]","[Support, Nuker, Disabler, Escape]","[Carry, Nuker, Disabler, Durable, Escape, Init...","[Support, Nuker, Disabler, Escape]","[Support, Nuker, Escape, Disabler]","[Carry, Escape, Nuker, Disabler]","[Support, Nuker, Disabler, Escape]","[Carry, Initiator, Disabler, Durable]","[Support, Nuker, Escape, Disabler]","[Carry, Durable]","[Support, Carry, Initiator, Disabler, Escape]","[Initiator, Durable, Disabler]","[Carry, Nuker, Disabler]"
img,/apps/dota2/images/dota_react/heroes/antimage....,/apps/dota2/images/dota_react/heroes/axe.png?,/apps/dota2/images/dota_react/heroes/bane.png?,/apps/dota2/images/dota_react/heroes/bloodseek...,/apps/dota2/images/dota_react/heroes/crystal_m...,/apps/dota2/images/dota_react/heroes/drow_rang...,/apps/dota2/images/dota_react/heroes/earthshak...,/apps/dota2/images/dota_react/heroes/juggernau...,/apps/dota2/images/dota_react/heroes/mirana.png?,/apps/dota2/images/dota_react/heroes/morphling...,/apps/dota2/images/dota_react/heroes/nevermore...,/apps/dota2/images/dota_react/heroes/phantom_l...,/apps/dota2/images/dota_react/heroes/puck.png?,/apps/dota2/images/dota_react/heroes/pudge.png?,/apps/dota2/images/dota_react/heroes/razor.png?,/apps/dota2/images/dota_react/heroes/sand_king...,/apps/dota2/images/dota_react/heroes/storm_spi...,/apps/dota2/images/dota_react/heroes/sven.png?,/apps/dota2/images/dota_react/heroes/tiny.png?,/apps/dota2/images/dota_react/heroes/vengefuls...,/apps/dota2/images/dota_react/heroes/windrunne...,/apps/dota2/images/dota_react/heroes/zuus.png?,/apps/dota2/images/dota_react/heroes/kunkka.png?,/apps/dota2/images/dota_react/heroes/lina.png?,/apps/dota2/images/dota_react/heroes/lion.png?,/apps/dota2/images/dota_react/heroes/shadow_sh...,/apps/dota2/images/dota_react/heroes/slardar.png?,/apps/dota2/images/dota_react/heroes/tidehunte...,/apps/dota2/images/dota_react/heroes/witch_doc...,/apps/dota2/images/dota_react/heroes/lich.png?,/apps/dota2/images/dota_react/heroes/riki.png?,/apps/dota2/images/dota_react/heroes/enigma.png?,/apps/dota2/images/dota_react/heroes/tinker.png?,/apps/dota2/images/dota_react/heroes/sniper.png?,/apps/dota2/images/dota_react/heroes/necrolyte...,/apps/dota2/images/dota_react/heroes/warlock.png?,/apps/dota2/images/dota_react/heroes/beastmast...,/apps/dota2/images/dota_react/heroes/queenofpa...,/apps/dota2/images/dota_react/heroes/venomance...,/apps/dota2/images/dota_react/heroes/faceless_...,/apps/dota2/images/dota_react/heroes/skeleton_...,/apps/dota2/images/dota_react/heroes/death_pro...,/apps/dota2/images/dota_react/heroes/phantom_a...,/apps/dota2/images/dota_react/heroes/pugna.png?,/apps/dota2/images/dota_react/heroes/templar_a...,/apps/dota2/images/dota_react/heroes/viper.png?,/apps/dota2/images/dota_react/heroes/luna.png?,/apps/dota2/images/dota_react/heroes/dragon_kn...,/apps/dota2/images/dota_react/heroes/dazzle.png?,/apps/dota2/images/dota_react/heroes/rattletra...,...,/apps/dota2/images/dota_react/heroes/lycan.png?,/apps/dota2/images/dota_react/heroes/brewmaste...,/apps/dota2/images/dota_react/heroes/shadow_de...,/apps/dota2/images/dota_react/heroes/lone_drui...,/apps/dota2/images/dota_react/heroes/chaos_kni...,/apps/dota2/images/dota_react/heroes/meepo.png?,/apps/dota2/images/dota_react/heroes/treant.png?,/apps/dota2/images/dota_react/heroes/ogre_magi...,/apps/dota2/images/dota_react/heroes/undying.png?,/apps/dota2/images/dota_react/heroes/rubick.png?,/apps/dota2/images/dota_react/heroes/disruptor...,/apps/dota2/images/dota_react/heroes/nyx_assas...,/apps/dota2/images/dota_react/heroes/naga_sire...,/apps/dota2/images/dota_react/heroes/keeper_of...,/apps/dota2/images/dota_react/heroes/wisp.png?,/apps/dota2/images/dota_react/heroes/visage.png?,/apps/dota2/images/dota_react/heroes/slark.png?,/apps/dota2/images/dota_react/heroes/medusa.png?,/apps/dota2/images/dota_react/heroes/troll_war...,/apps/dota2/images/dota_react/heroes/centaur.png?,/apps/dota2/images/dota_react/heroes/magnataur...,/apps/dota2/images/dota_react/heroes/shredder....,/apps/dota2/images/dota_react/heroes/bristleba...,/apps/dota2/images/dota_react/heroes/tusk.png?,/apps/dota2/images/dota_react/heroes/skywrath_...,/apps/dota2/images/dota_react/heroes/abaddon.png?,/apps/dota2/images/dota_react/heroes/elder_tit...,/apps/dota2/images/dota_react/heroes/legion_co...,/apps/dota2/images/dota_react/heroes/techies.png?,/apps/dota2/images/dota_react/heroes/ember_spi...,/apps/dota2/images/dota_react/heroes/earth_spi...,/apps/dota2/images/dota_react/heroes/abyssal_u...,/apps/dota2/images/dota_react/heroes/terrorbla...,/apps/dota2/images/dota_react/heroes/phoenix.png?,/apps/dota2/images/dota_react/heroes/oracle.png?,/apps/dota2/images/dota_react/heroes/winter_wy...,/apps/dota2/images/dota_react/heroes/arc_warde...,/apps/dota2/images/dota_react/heroes/monkey_ki...,/apps/dota2/images/dota_react/heroes/dark_will...,/apps/dota2/images/dota_react/heroes/pangolier...,/apps/dota2/images/dota_react/heroes/grimstrok...,/apps/dota2/images/dota_react/heroes/hoodwink....,/apps/dota2/images/dota_react/heroes/void_spir...,/apps/dota2/images/dota_react/heroes/snapfire....,/apps/dota2/images/dota_react/heroes/mars.png?,/apps/dota2/images/dota_react/heroes/ringmaste...,/apps/dota2/images/dota_react/heroes/dawnbreak...,/apps/dota2/images/dota_react/heroes/marci.png?,/apps/dota2/images/dota_react/heroes/primal_be...,/apps/dota2/images/dota_react/heroes/muerta.png?
icon,/apps/dota2/images/dota_react/heroes/icons/ant...,/apps/dota2/images/dota_react/heroes/icons/axe...,/apps/dota2/images/dota_react/heroes/icons/ban...,/apps/dota2/images/dota_react/heroes/icons/blo...,/apps/dota2/images/dota_react/heroes/icons/cry...,/apps/dota2/images/dota_react/heroes/icons/dro...,/apps/dota2/images/dota_react/heroes/icons/ear...,/apps/dota2/images/dota_react/heroes/icons/jug...,/apps/dota2/images/dota_react/heroes/icons/mir...,/apps/dota2/images/dota_react/heroes/icons/mor...,/apps/dota2/images/dota_react/heroes/icons/nev...,/apps/dota2/images/dota_react/heroes/icons/pha...,/apps/dota2/images/dota_react/heroes/icons/puc...,/apps/dota2/images/dota_react/heroes/icons/pud...,/apps/dota2/images/dota_react/heroes/icons/raz...,/apps/dota2/images/dota_react/heroes/icons/san...,/apps/dota2/images/dota_react/heroes/icons/sto...,/apps/dota2/images/dota_react/heroes/icons/sve...,/apps/dota2/images/dota_react/heroes/icons/tin...,/apps/dota2/images/dota_react/heroes/icons/ven...,/apps/dota2/images/dota_react/heroes/icons/win...,/apps/dota2/images/dota_react/heroes/icons/zuu...,/apps/dota2/images/dota_react/heroes/icons/kun...,/apps/dota2/images/dota_react/heroes/icons/lin...,/apps/dota2/images/dota_react/heroes/icons/lio...,/apps/dota2/images/dota_react/heroes/icons/sha...,/apps/dota2/images/dota_react/heroes/icons/sla...,/apps/dota2/images/dota_react/heroes/icons/tid...,/apps/dota2/images/dota_react/heroes/icons/wit...,/apps/dota2/images/dota_react/heroes/icons/lic...,/apps/dota2/images/dota_react/heroes/icons/rik...,/apps/dota2/images/dota_react/heroes/icons/eni...,/apps/dota2/images/dota_react/heroes/icons/tin...,/apps/dota2/images/dota_react/heroes/icons/sni...,/apps/dota2/images/dota_react/heroes/icons/nec...,/apps/dota2/images/dota_react/heroes/icons/war...,/apps/dota2/images/dota_react/heroes/icons/bea...,/apps/dota2/images/dota_react/heroes/icons/que...,/apps/dota2/images/dota_react/heroes/icons/ven...,/apps/dota2/images/dota_react/heroes/icons/fac...,/apps/dota2/images/dota_react/heroes/icons/ske...,/apps/dota2/images/dota_react/heroes/icons/dea...,/apps/dota2/images/dota_react/heroes/icons/pha...,/apps/dota2/images/dota_react/heroes/icons/pug...,/apps/dota2/images/dota_react/heroes/icons/tem...,/apps/dota2/images/dota_react/heroes/icons/vip...,/apps/dota2/images/dota_react/heroes/icons/lun...,/apps/dota2/images/dota_react/heroes/icons/dra...,/apps/dota2/images/dota_react/heroes/icons/daz...,/apps/dota2/images/dota_react/heroes/icons/rat...,...,/apps/dota2/images/dota_react/heroes/icons/lyc...,/apps/dota2/images/dota_react/heroes/icons/bre...,/apps/dota2/images/dota_react/heroes/icons/sha...,/apps/dota2/images/dota_react/heroes/icons/lon...,/apps/dota2/images/dota_react/heroes/icons/cha...,/apps/dota2/images/dota_react/heroes/icons/mee...,/apps/dota2/images/dota_react/heroes/icons/tre...,/apps/dota2/images/dota_react/heroes/icons/ogr...,/apps/dota2/images/dota_react/heroes/icons/und...,/apps/dota2/images/dota_react/heroes/icons/rub...,/apps/dota2/images/dota_react/heroes/icons/dis...,/apps/dota2/images/dota_react/heroes/icons/nyx...,/apps/dota2/images/dota_react/heroes/icons/nag...,/apps/dota2/images/dota_react/heroes/icons/kee...,/apps/dota2/images/dota_react/heroes/icons/wis...,/apps/dota2/images/dota_react/heroes/icons/vis...,/apps/dota2/images/dota_react/heroes/icons/sla...,/apps/dota2/images/dota_react/heroes/icons/med...,/apps/dota2/images/dota_react/heroes/icons/tro...,/apps/dota2/images/dota_react/heroes/icons/cen...,/apps/dota2/images/dota_react/heroes/icons/mag...,/apps/dota2/images/dota_react/heroes/icons/shr...,/apps/dota2/images/dota_react/heroes/icons/bri...,/apps/dota2/images/dota_react/heroes/icons/tus...,/apps/dota2/images/dota_react/heroes/icons/sky...,/apps/dota2/images/dota_react/heroes/icons/aba...,/apps/dota2/images/dota_react/heroes/icons/eld...,/apps/dota2/images/dota_react/heroes/icons/leg...,/apps/dota2/images/dota_react/heroes/icons/tec...,/apps/dota2/images/dota_react/heroes/icons/emb...,/apps/dota2/images/dota_react/heroes/icons/ear...,/apps/dota2/images/dota_react/heroes/icons/aby...,/apps/dota2/images/dota_react/heroes/icons/ter...,/apps/dota2/images/dota_react/heroes/icons/pho...,/apps/dota2/images/dota_react/heroes/icons/ora...,/apps/dota2/images/dota_react/heroes/icons/win...,/apps/dota2/images/dota_react/heroes/icons/arc...,/apps/dota2/images/dota_react/heroes/icons/mon...,/apps/dota2/images/dota_react/heroes/icons/dar...,/apps/dota2/images/dota_react/heroes/icons/pan...,/apps/dota2/images/dota_react/heroes/icons/gri...,/apps/dota2/images/dota_react/heroes/icons/hoo...,/apps/dota2/images/dota_react/heroes/icons/voi...,/apps/dota2/images/dota_react/heroes/icons/sna...,/apps/dota2/images/dota_react/heroes/icons/mar...,/apps/dota2/images/dota_react/heroes/icons/rin...,/apps/dota2/images/dota_react/heroes/icons/daw...,/apps/dota2/images/dota_react/heroes/icons/mar...,/apps/dota2/images/dota_react/heroes/icons/pri...,/apps/dota2/images/dota_react/heroes/icons/mue...
base_health,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,...,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
base_health_regen,1,2.5,0.25,0.25,0.25,0.25,1,0.5,0.25,0.5,0.25,1.5,0.5,2.5,1,0.25,0.5,0.75,2,0.25,0.25,0.25,0.75,0.25,0.5,1,0.5,0.25,0.25,0.5,2.5,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,1,0.5,0.25,1,0.25,1,0.25,0.5,0.25,0.25,0.5,...,0.25,0.5,0.25,0.25,0.25,0.25,0.25,1.5,None,0.25,0.25,2,1,0.25,0.25,0.25,0.25,0.25,0.25,3,0.5,0.25,1,1,0.25,1,0.75,0.25,1,0.5,1,0.25,1.5,2,0.25,0.25,0.25,1,0.75,1.25,0.25,0.25,0.25,0.75,0.25,0.25,0.25,0.25,0.25,0.25
base_mana,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,...,75,75,75,75,75,75,75,120,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
base_mana_regen,0,0,0,0,0,0,0,0,0.4,0.5,0.3,0,0.5,0,0,0,0,0,0,0,0.25,0,0,0,0,0,0,0.5,0,0.75,0,0.5,0.75,0,0,0,0,0,0,0,0,0.5,0,0.5,0,0,0,0,0.3,0,...,0,0,0,0,0,0.25,0.25,0,0.25,0.5,0,0,0,0,0,0,0,0,0,0,0.5,0.5,0.4,0.5,0.25,0.25,0.25,0,1,0,0,0,0,0,0.5,0.5,0,0,0,0,0,0,0.6,0,0.5,0,0,0,0,0
base_armor,1,0,1,2,0,0,2,0,-2,-2,1,0,0,0,0,1,1,-1,0,0,0,2,2,0,0,3,3,0,0,-1,0,1,4,-1,2,1,-1,0,0,0,-1,1,1,0,0,-2,2,0,0,1,...,0,0,0,0,2,4,-1,4,1,1,0,1,1,0,1,0,0,-1,-1,-2,1,0,1,1,-2,0,0,0,2,0,0,3,5,-1,1,1,0,2,0,2,0,0,-1,1,-1,1,2,0,2,0
base_mr,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25

In [20]:
heroes_constants_transposed = heroes_constants.T
hero_dict = heroes_constants_transposed.set_index('id')['localized_name'].to_dict()
hero_dict

{1: 'Anti-Mage',
 2: 'Axe',
 3: 'Bane',
 4: 'Bloodseeker',
 5: 'Crystal Maiden',
 6: 'Drow Ranger',
 7: 'Earthshaker',
 8: 'Juggernaut',
 9: 'Mirana',
 10: 'Morphling',
 11: 'Shadow Fiend',
 12: 'Phantom Lancer',
 13: 'Puck',
 14: 'Pudge',
 15: 'Razor',
 16: 'Sand King',
 17: 'Storm Spirit',
 18: 'Sven',
 19: 'Tiny',
 20: 'Vengeful Spirit',
 21: 'Windranger',
 22: 'Zeus',
 23: 'Kunkka',
 25: 'Lina',
 26: 'Lion',
 27: 'Shadow Shaman',
 28: 'Slardar',
 29: 'Tidehunter',
 30: 'Witch Doctor',
 31: 'Lich',
 32: 'Riki',
 33: 'Enigma',
 34: 'Tinker',
 35: 'Sniper',
 36: 'Necrophos',
 37: 'Warlock',
 38: 'Beastmaster',
 39: 'Queen of Pain',
 40: 'Venomancer',
 41: 'Faceless Void',
 42: 'Wraith King',
 43: 'Death Prophet',
 44: 'Phantom Assassin',
 45: 'Pugna',
 46: 'Templar Assassin',
 47: 'Viper',
 48: 'Luna',
 49: 'Dragon Knight',
 50: 'Dazzle',
 51: 'Clockwerk',
 52: 'Leshrac',
 53: "Nature's Prophet",
 54: 'Lifestealer',
 55: 'Dark Seer',
 56: 'Clinkz',
 57: 'Omniknight',
 58: 'Enchantress',
 59: 'Huskar',
 60: 'Night Stalker',
 61: 'Broodmother',
 62: 'Bounty Hunter',
 63: 'Weaver',
 64: 'Jakiro',
 65: 'Batrider',
 66: 'Chen',
 67: 'Spectre',
 68: 'Ancient Apparition',
 69: 'Doom',
 70: 'Ursa',
 71: 'Spirit Breaker',
 72: 'Gyrocopter',
 73: 'Alchemist',
 74: 'Invoker',
 75: 'Silencer',
 76: 'Outworld Devourer',
 77: 'Lycan',
 78: 'Brewmaster',
 79: 'Shadow Demon',
 80: 'Lone Druid',
 81: 'Chaos Knight',
 82: 'Meepo',
 83: 'Treant Protector',
 84: 'Ogre Magi',
 85: 'Undying',
 86: 'Rubick',
 87: 'Disruptor',
 88: 'Nyx Assassin',
 89: 'Naga Siren',
 90: 'Keeper of the Light',
 91: 'Io',
 92: 'Visage',
 93: 'Slark',
 94: 'Medusa',
 95: 'Troll Warlord',
 96: 'Centaur Warrunner',
 97: 'Magnus',
 98: 'Timbersaw',
 99: 'Bristleback',
 100: 'Tusk',
 101: 'Skywrath Mage',
 102: 'Abaddon',
 103: 'Elder Titan',
 104: 'Legion Commander',
 105: 'Techies',
 106: 'Ember Spirit',
 107: 'Earth Spirit',
 108: 'Underlord',
 109: 'Terrorblade',
 110: 'Phoenix',
 111: 'Oracle',
 112: 'Winter Wyvern',
 113: 'Arc Warden',
 114: 'Monkey King',
 119: 'Dark Willow',
 120: 'Pangolier',
 121: 'Grimstroke',
 123: 'Hoodwink',
 126: 'Void Spirit',
 128: 'Snapfire',
 129: 'Mars',
 131: 'Ring Master',
 135: 'Dawnbreaker',
 136: 'Marci',
 137: 'Primal Beast',
 138: 'Muerta'}

# League Games

In [21]:
leagues = get_opendota_df('leagues')
league_tiers = leagues['tier'].unique()
league_tiers

array(['professional', 'premium', 'excluded', 'amateur', None],
      dtype=object)

In [22]:
premium_leagues = leagues[leagues['tier']=='premium'].sort_values(by='leagueid', ascending=False)
professional_leagues = leagues[leagues['tier']=='professional'].sort_values(by='leagueid', ascending=False)

In [23]:
premium_leagues[:20]

,leagueid,ticket,banner,tier,name
7046,16935,None,None,premium,The International 2024
1881,15728,None,None,premium,The International 2023
1812,15694,None,None,premium,Road to TI 2023 - SEA Regional Qualifiers
1811,15693,None,None,premium,Road to TI 2023 - WEU Regional Qualifiers
1810,15692,None,None,premium,Road to TI 2023 - SA Regional Qualifiers
1809,15691,None,None,premium,Road to TI 2023 - EEU Regional Qualifiers
1808,15690,None,None,premium,Road to TI 2023 - NA Regional Qualifiers
1788,15689,None,None,premium,Road to TI 2023 - CN Regional Qualifiers
5134,15438,None,None,premium,The Bali Major
1520,15385,None,None,premium,DPC 2023 CN Summer Tour Closed Qualifiers - pr...
1519,15384,None,None,premium,DPC 2023 CN Summer Tour Division II - presente...
1518,15383,None,None,premium,DPC 2023 CN Summer Tour Division I - presented...
1516,15377,None,None,premium,DPC 2023 SEA Summer Tour Closed Qualifiers - p...
1514,15375,None,None,premium,DPC 2023 SEA Summer Tour Division II - present...
6208,15374,None,None,premium,DPC 2023 SEA Summer Tour Division I - presente...
1508,15366,None,None,premium,DPC 2023 SA Summer Tour Division II – presente...
1471,15365,None,None,premium,DPC 2023 SA Summer Tour Division I – presented...
1470,15364,None,None,premium,DPC 2023 SA Summer Tour Closed Qualifiers – pr...
1463,15353,None,None,premium,DPC 2023 NA Summer Tour Division II – presente...
1462,15352,None,None,premium,DPC 2023 WEU Summer Tour Division II – present...

In [24]:
professional_leagues[:20]

,leagueid,ticket,banner,tier,name
7473,65019,None,None,professional,BanglaGamer Dota 2 Championship
7472,65018,None,None,professional,GameLadders DOTA 2 League
3921,65013,econ/leagues/subscriptions_mlgd2,econ/leagues/subscriptions_mlgna_ingame,professional,"MLG $50,000 Dota 2 Championship"
7471,65010,None,None,professional,AMD DOTA 2 Beginner’s Challenge
3546,65008,econ/leagues/subscriptions_nest,econ/leagues/subscriptions_nest_ingame,professional,2013 National Electronic Sports Tournament
7280,65007,econ/leagues/subscriptions_nexon_starter,econ/leagues/subscriptions_nexon_starter_ingame,professional,Nexon Starter League
7470,65006,None,None,professional,The International 2013
3541,65005,econ/leagues/subscriptions_westqualifier_ingame,econ/leagues/subscriptions_westqualifier_ingame,professional,The International West Qualifiers
3612,65004,econ/leagues/subscriptions_eastqualifier_ingame,econ/leagues/subscriptions_eastqualifier_ingame,professional,The International East Qualifiers
6678,65002,econ/leagues/subscriptions_dreamhack_winter2012,econ/leagues/subscriptions_dreamhack_winter201...,professional,DreamHack Dota 2 Corsair Vengeance Cup
7049,65001,econ/leagues/subscriptions_international_ingame,econ/leagues/subscriptions_international_ingame,professional,The International 2012
6543,17104,None,None,professional,EPICENTER - 8° TORNEO UNSCH
6762,17074,None,None,professional,Bitel True Fighters 2024
7169,17064,None,None,professional,Royal Circuit #3
7168,17063,None,None,professional,Royal Circuit #2
7164,17059,None,None,professional,Phoenix League
7161,17056,None,None,professional,CCT Dota 2 Series 3
7148,17041,None,None,professional,E - Gaming League
7140,17030,None,None,professional,Open Esports Student Games
7131,17021,None,None,professional,Culling Blade League

## Teams

In [25]:
team_id = 8766104
endpoint = f"/teams/{team_id}/matches"

In [26]:
team = get_opendota_df(endpoint)
team

Empty DataFrame
Columns: []
Index: []

# With API_KEY

In [90]:
from src.fetch_data import get_match_details

match_id = 7876840316

res = get_match_details(match_id)
res

middlewares.track_api - API usage updated: {'20240831': 1, 'count': 1975, 'last_reset_date': '20240901'}

{'version': 21,
 'match_id': 7876840316,
 'draft_timings': [{'order': 1,
   'pick': False,
   'active_team': 3,
   'hero_id': 220,
   'player_slot': None,
   'extra_time': 130,
   'total_time_taken': 27},
  {'order': 2,
   'pick': False,
   'active_team': 2,
   'hero_id': 142,
   'player_slot': None,
   'extra_time': 25,
   'total_time_taken': 125},
  {'order': 3,
   'pick': False,
   'active_team': 2,
   'hero_id': 76,
   'player_slot': None,
   'extra_time': 123,
   'total_time_taken': 6},
  {'order': 4,
   'pick': False,
   'active_team': 3,
   'hero_id': 114,
   'player_slot': None,
   'extra_time': 25,
   'total_time_taken': 8},
  {'order': 5,
   'pick': False,
   'active_team': 2,
   'hero_id': 246,
   'player_slot': None,
   'extra_time': 25,
   'total_time_taken': 11},
  {'order': 6,
   'pick': False,
   'active_team': 2,
   'hero_id': 38,
   'player_slot': None,
   'extra_time': 123,
   'total_time_taken': 19},
  {'order': 7,
   'pick': False,
   'active_team': 3,
   'hero_id': 256,
   'player_slot': None,
   'extra_time': 123,
   'total_time_taken': 12},
  {'order': 8,
   'pick': True,
   'active_team': 3,
   'hero_id': 126,
   'player_slot': 5,
   'extra_time': 25,
   'total_time_taken': 1},
  {'order': 9,
   'pick': True,
   'active_team': 2,
   'hero_id': 102,
   'player_slot': 4,
   'extra_time': 123,
   'total_time_taken': 8},
  {'order': 10,
   'pick': False,
   'active_team': 3,
   'hero_id': 34,
   'player_slot': None,
   'extra_time': 123,
   'total_time_taken': 17},
  {'order': 11,
   'pick': False,
   'active_team': 3,
   'hero_id': 140,
   'player_slot': None,
   'extra_time': 25,
   'total_time_taken': 17},
  {'order': 12,
   'pick': False,
   'active_team': 2,
   'hero_id': 112,
   'player_slot': None,
   'extra_time': 25,
   'total_time_taken': 22},
  {'order': 13,
   'pick': True,
   'active_team': 2,
   'hero_id': 158,
   'player_slot': 0,
   'extra_time': 123,
   'total_time_taken': 1},
  {'order': 14,
   'pick': True,
   'active_team': 3,
   'hero_id': 172,
   'player_slot': 7,
   'extra_time': 108,
   'total_time_taken': 45},
  {'order': 15,
   'pick': True,
   'active_team': 3,
   'hero_id': 78,
   'player_slot': 8,
   'extra_time': 25,
   'total_time_taken': 13},
  {'order': 16,
   'pick': True,
   'active_team': 2,
   'hero_id': 212,
   'player_slot': 1,
   'extra_time': 25,
   'total_time_taken': 12},
  {'order': 17,
   'pick': True,
   'active_team': 2,
   'hero_id': 46,
   'player_slot': 3,
   'extra_time': 108,
   'total_time_taken': 48},
  {'order': 18,
   'pick': True,
   'active_team': 3,
   'hero_id': 258,
   'player_slot': 6,
   'extra_time': 91,
   'total_time_taken': 46},
  {'order': 19,
   'pick': False,
   'active_team': 3,
   'hero_id': 190,
   'player_slot': None,
   'extra_time': 7,
   'total_time_taken': 35},
  {'order': 20,
   'pick': False,
   'active_team': 2,
   'hero_id': 144,
   'player_slot': None,
   'extra_time': 7,
   'total_time_taken': 22},
  {'order': 21,
   'pick': False,
   'active_team': 2,
   'hero_id': 92,
   'player_slot': None,
   'extra_time': 86,
   'total_time_taken': 29},
  {'order': 22,
   'pick': False,
   'active_team': 3,
   'hero_id': 82,
   'player_slot': None,
   'extra_time': 65,
   'total_time_taken': 51},
  {'order': 23,
   'pick': True,
   'active_team': 3,
   'hero_id': 228,
   'player_slot': 9,
   'extra_time': 7,
   'total_time_taken': 80},
  {'order': 24,
   'pick': True,
   'active_team': 2,
   'hero_id': 108,
   'player_slot': 2,
   'extra_time': 7,
   'total_time_taken': 21}],
 'teamfights': [{'start': 797,
   'end': 833,
   'last_death': 818,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'shadow_demon_shadow_poison': 4,
      'shadow_demon_shadow_poison_release': 1},
     'ability_targets': {},
     'item_uses': {'arcane_boots': 1, 'arcane_ring': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 252,
     'xp_delta': 459,
     'xp_start': 4044,
     'xp_end': 4503},
    {'deaths_pos': {},
     'ability_uses': {'ember_spirit_sleight_of_fist': 2,
      'ember_spirit_searing_chains': 1,
      'ember_spirit_fire_remnant': 2,
      'ember_spirit_activate_fire_remnant': 1,
      'ember_spirit_flame_guard': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3, 'magic_wand': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 895,
     'healing': 165,
     'gold_delta': 309,
     'xp_delta': 1172,
     'xp_start': 5322,
     'xp_end': 6437},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_open_wounds': 1,
      'life_stealer_infest': 1,
      'life_stealer_unfettered': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3, 'quelling_blade': 1},
     'killed': {'npc_dota_hero_mars': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 757,
     'healing': 563,
     'gold_delta': 336,
     'xp_delta': 734,
     'xp_start': 5562,
     'xp_end': 6296},
    {'deaths_pos': {'127.9': {'126.4': 1}},
     'ability_uses': {'kunkka_x_marks_the_spot': 1,
      'kunkka_torrent': 1,
      'kunkka_return': 1,
      'kunkka_ghostship': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3, 'blade_mail': 1},
     'killed': {'npc_dota_hero_queenofpain': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1711,
     'healing': 0,
     'gold_delta': 176,
     'xp_delta': 94,
     'xp_start': 5884,
     'xp_end': 5978},
    {'deaths_pos': {},
     'ability_uses': {'rattletrap_rocket_flare': 1},
     'ability_targets': {},
     'item_uses': {'arcane_ring': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 424,
     'healing': 0,
     'gold_delta': 472,
     'xp_delta': 237,
     'xp_start': 2818,
     'xp_end': 3055},
    {'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 3, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 2, 'magic_stick': 1, 'urn_of_shadows': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 366,
     'healing': 0,
     'gold_delta': 227,
     'xp_delta': 521,
     'xp_start': 2125,
     'xp_end': 2645},
    {'deaths_pos': {'183.3': {'128.4': 1}},
     'ability_uses': {'mars_gods_rebuke': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 2},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 184,
     'healing': 0,
     'gold_delta': -137,
     'xp_delta': 59,
     'xp_start': 4315,
     'xp_end': 4372},
    {'deaths_pos': {},
     'ability_uses': {'rubick_spell_steal': 1,
      'kunkka_x_marks_the_spot': 1,
      'rubick_fade_bolt': 2,
      'rubick_telekinesis': 1,
      'rubick_telekinesis_land': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 1, 'arcane_boots': 1, 'arcane_ring': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 341,
     'healing': 0,
     'gold_delta': 145,
     'xp_delta': 598,
     'xp_start': 3527,
     'xp_end': 4124},
    {'deaths_pos': {'126.1': {'126.5': 1}},
     'ability_uses': {'queenofpain_shadow_strike': 2,
      'queenofpain_scream_of_pain': 2,
      'queenofpain_blink': 1,
      'queenofpain_sonic_wave': 1},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1, 'dagon': 1},
     'killed': {'npc_dota_hero_kunkka': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1786,
     'healing': 497,
     'gold_delta': 198,
     'xp_delta': 83,
     'xp_start': 6417,
     'xp_end': 6499},
    {'deaths_pos': {},
     'ability_uses': {'monkey_king_tree_dance': 2,
      'monkey_king_primal_spring': 2},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 213,
     'xp_delta': 393,
     'xp_start': 5176,
     'xp_end': 5536}]},
  {'start': 901,
   'end': 942,
   'last_death': 927,
   'deaths': 4,
   'players': [{'deaths_pos': {'112.5': {'140.6': 1}},
     'ability_uses': {'shadow_demon_disruption': 1,
      'shadow_demon_disseminate': 1,
      'shadow_demon_demonic_purge': 1,
      'shadow_demon_shadow_poison': 5,
      'shadow_demon_shadow_poison_release': 2},
     'ability_targets': {},
     'item_uses': {'blink': 1, 'magic_wand': 1},
     'killed': {'npc_dota_hero_rubick': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1313,
     'healing': 135,
     'gold_delta': 417,
     'xp_delta': 854,
     'xp_start': 6188,
     'xp_end': 7042},
    {'deaths_pos': {},
     'ability_uses': {'ember_spirit_flame_guard': 1,
      'ember_spirit_searing_chains': 2,
      'ember_spirit_sleight_of_fist': 3,
      'ember_spirit_fire_remnant': 1,
      'ember_spirit_activate_fire_remnant': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3, 'bottle': 3, 'ward_dispenser': 2},
     'killed': {'npc_dota_hero_queenofpain': 1, 'npc_dota_hero_weaver': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 2485,
     'healing': 85,
     'gold_delta': 992,
     'xp_delta': 1350,
     'xp_start': 7116,
     'xp_end': 8409},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'phase_boots': 4, 'quelling_blade': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 375,
     'gold_delta': 477,
     'xp_delta': 573,
     'xp_start': 7149,
     'xp_end': 7722},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_torrent': 2,
      'kunkka_x_marks_the_spot': 1,
      'kunkka_ghostship': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 255,
     'healing': 0,
     'gold_delta': 353,
     'xp_delta': 677,
     'xp_start': 6512,
     'xp_end': 7132},
    {'deaths_pos': {},
     'ability_uses': {'rattletrap_battery_assault': 2,
      'rattletrap_hookshot': 1,
      'rattletrap_power_cogs': 2,
      'rattletrap_rocket_flare': 1},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1, 'dust': 1, 'arcane_ring': 1},
     'killed': {'npc_dota_hero_shadow_demon': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 582,
     'healing': 195,
     'gold_delta': 325,
     'xp_delta': 122,
     'xp_start': 4490,
     'xp_end': 4612},
    {'deaths_pos': {'121.5': {'137.1': 1}},
     'ability_uses': {'weaver_the_swarm': 1,
      'weaver_shukuchi': 2,
      'weaver_time_lapse': 1},
     'ability_targets': {},
     'item_uses': {'magic_stick': 1,
      'enchanted_mango': 1,
      'urn_of_shadows': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 695,
     'healing': 90,
     'gold_delta': -67,
     'xp_delta': 11,
     'xp_start': 2796,
     'xp_end': 2806},
    {'deaths_pos': {},
     'ability_uses': {'mars_gods_rebuke': 2, 'mars_spear': 1},
     'ability_targets': {},
     'item_uses': {'quelling_blade': 1, 'phase_boots': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 258,
     'xp_delta': 432,
     'xp_start': 4972,
     'xp_end': 5404},
    {'deaths_pos': {'120.4': {'139': 1}},
     'ability_uses': {'rubick_fade_bolt': 2,
      'rubick_telekinesis': 1,
      'rubick_telekinesis_land': 1,
      'rubick_spell_steal': 1,
      'rattletrap_hookshot': 1},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1, 'famango': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 891,
     'healing': 411,
     'gold_delta': -65,
     'xp_delta': 11,
     'xp_start': 4656,
     'xp_end': 4666},
    {'deaths_pos': {'123': {'142.6': 1}},
     'ability_uses': {'queenofpain_blink': 2,
      'queenofpain_shadow_strike': 2,
      'queenofpain_scream_of_pain': 2},
     'ability_targets': {},
     'item_uses': {'dagon': 1, 'magic_wand': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1723,
     'healing': 536,
     'gold_delta': -127,
     'xp_delta': 1147,
     'xp_start': 6878,
     'xp_end': 8024},
    {'deaths_pos': {},
     'ability_uses': {'monkey_king_tree_dance': 1,
      'monkey_king_primal_spring': 1,
      'monkey_king_primal_spring_early': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 239,
     'xp_delta': 539,
     'xp_start': 6442,
     'xp_end': 6924}]},
  {'start': 984,
   'end': 1037,
   'last_death': 1022,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'shadow_demon_shadow_poison': 9,
      'shadow_demon_disseminate': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 2,
      'arcane_boots': 1,
      'arcane_ring': 1,
      'blink': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 269,
     'healing': 0,
     'gold_delta': 408,
     'xp_delta': 1005,
     'xp_start': 7112,
     'xp_end': 8116},
    {'deaths_pos': {},
     'ability_uses': {'ember_spirit_sleight_of_fist': 4,
      'ember_spirit_searing_chains': 1,
      'ember_spirit_flame_guard': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 3, 'bottle': 4},
     'killed': {'npc_dota_hero_rubick': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1637,
     'healing': 228,
     'gold_delta': 671,
     'xp_delta': 855,
     'xp_start': 8994,
     'xp_end': 9847},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_consume': 1,
      'life_stealer_open_wounds': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'quelling_blade': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1137,
     'healing': 313,
     'gold_delta': 575,
     'xp_delta': 1125,
     'xp_start': 8450,
     'xp_end': 9575},
    {'deaths_pos': {},
     'ability_uses': {'kunkka_x_marks_the_spot': 1,
      'kunkka_torrent': 1,
      'kunkka_ghostship': 1,
      'kunkka_return': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 6, 'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 998,
     'healing': 0,
     'gold_delta': 546,
     'xp_delta': 760,
     'xp_start': 7932,
     'xp_end': 8692},
    {'deaths_pos': {},
     'ability_uses': {'rattletrap_rocket_flare': 1,
      'rattletrap_hookshot': 1,
      'rattletrap_battery_assault': 1,
      'rattletrap_power_cogs': 2},
     'ability_targets': {},
     'item_uses': {'arcane_ring': 1, 'ward_dispenser': 4, 'ward_observer': 1},
     'killed': {'npc_dota_hero_mars': 1, 'npc_dota_hero_queenofpain': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 814,
     'healing': 0,
     'gold_delta': 735,
     'xp_delta': 727,
     'xp_start': 4802,
     'xp_end': 5528},
    {'deaths_pos': {},
     'ability_uses': {'weaver_shukuchi': 4, 'weaver_the_swarm': 1},
     'ability_targets': {},
     'item_uses': {'trusty_shovel': 1, 'ward_observer': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 0,
     'xp_delta': 0,
     'xp_start': 2928,
     'xp_end': 2928},
    {'deaths_pos': {'151.9': {'124.8': 1}},
     'ability_uses': {'mars_gods_rebuke': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 225,
     'healing': 0,
     'gold_delta': -178,
     'xp_delta': 0,
     'xp_start': 6271,
     'xp_end': 6271},
    {'deaths_pos': {'134.6': {'140.2': 1}},
     'ability_uses': {'rubick_spell_steal': 1,
      'rubick_fade_bolt': 1,
      'ember_spirit_sleight_of_fist': 2},
     'ability_targets': {},
     'item_uses': {'arcane_ring': 1, 'arcane_boots': 1, 'ward_dispenser': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 377,
     'healing': 0,
     'gold_delta': -86,
     'xp_delta': 154,
     'xp_start': 4666,
     'xp_end': 4820},
    {'deaths_pos': {'119.5': {'128.3': 1}},
     'ability_uses': {'queenofpain_scream_of_pain': 3,
      'queenofpain_shadow_strike': 1,
      'queenofpain_blink': 1},
     'ability_targets': {},
     'item_uses': {},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 331,
     'healing': 114,
     'gold_delta': 251,
     'xp_delta': 639,
     'xp_start': 8502,
     'xp_end': 9141},
    {'deaths_pos': {},
     'ability_uses': {'monkey_king_tree_dance': 2,
      'monkey_king_primal_spring': 2},
     'ability_targets': {},
     'item_uses': {'power_treads': 3, 'bfury': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 27,
     'healing': 0,
     'gold_delta': 492,
     'xp_delta': 1061,
     'xp_start': 7720,
     'xp_end': 8781}]},
  {'start': 1114,
   'end': 1160,
   'last_death': 1145,
   'deaths': 3,
   'players': [{'deaths_pos': {},
     'ability_uses': {'shadow_demon_demonic_purge': 1,
      'shadow_demon_disseminate': 2,
      'shadow_demon_disruption': 1,
      'shadow_demon_shadow_poison': 6},
     'ability_targets': {},
     'item_uses': {'blink': 2,
      'arcane_boots': 1,
      'ward_sentry': 1,
      'magic_wand': 1,
      'arcane_ring': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1377,
     'healing': 90,
     'gold_delta': 561,
     'xp_delta': 916,
     'xp_start': 9190,
     'xp_end': 10105},
    {'deaths_pos': {'174': {'130.2': 1}},
     'ability_uses': {'ember_spirit_sleight_of_fist': 2,
      'ember_spirit_searing_chains': 2,
      'ember_spirit_flame_guard': 1,
      'ember_spirit_fire_remnant': 2,
      'ember_spirit_activate_fire_remnant': 2},
     'ability_targets': {},
     'item_uses': {'bottle': 3, 'magic_wand': 1, 'phase_boots': 1},
     'killed': {'npc_dota_hero_queenofpain': 1},
     'deaths': 1,
     'buybacks': 0,
     'damage': 2153,
     'healing': 246,
     'gold_delta': 528,
     'xp_delta': 1324,
     'xp_start': 10811,
     'xp_end': 12135},
    {'deaths_pos': {},
     'ability_uses': {'life_stealer_unfettered': 2,
      'life_stealer_open_wounds': 2,
      'ability_lamp_use': 1},
     'ability_targets': {},
     'item_uses': {'phase_boots': 6, 'quelling_blade': 1},
     'killed': {'npc_dota_hero_mars': 1},
     'deaths': 0,
     'buybacks': 0,
     'damage': 1633,
     'healing': 407,
     'gold_delta': 775,
     'xp_delta': 782,
     'xp_start': 10804,
     'xp_end': 11585},
    {'deaths_pos': {},
     'ability_uses': {},
     'ability_targets': {},
     'item_uses': {'phase_boots': 5, 'iron_talon': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 0,
     'healing': 0,
     'gold_delta': 729,
     'xp_delta': 853,
     'xp_start': 10344,
     'xp_end': 11197},
    {'deaths_pos': {},
     'ability_uses': {'plus_high_five': 1, 'rattletrap_power_cogs': 1},
     'ability_targets': {},
     'item_uses': {'magic_wand': 1, 'tpscroll': 1},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 286,
     'healing': 165,
     'gold_delta': 229,
     'xp_delta': 39,
     'xp_start': 5980,
     'xp_end': 6019},
    {'deaths_pos': {},
     'ability_uses': {'weaver_the_swarm': 1,
      'weaver_shukuchi': 5,
      'weaver_time_lapse': 1},
     'ability_targets': {},
     'item_uses': {'ward_dispenser': 2, 'ward_observer': 2},
     'killed': {},
     'deaths': 0,
     'buybacks': 0,
     'damage': 527,
     'healing': 0,
     'gold_delta': 235,
     'xp_delta': 758,
     'xp_start': 3160,
     'xp_end': 3916},
    {'deaths_pos': {'169.3': {'125.4': 1}},
     'ability_uses': {'mars_arena_of_blood': 1,
      'mars_spear': 3,
      'mars_gods_rebuke': 2},
     'ability_targets': {},
     'item_uses': {'orchid': 1, 'phase_boots': 3, 'quelling_blade': 1},
     'killed': {},
     'deaths': 1,
     'buybacks': 0,
     'damage': 1284,
     'healing': 0,
     'gold_delta': 15,
     'xp_delta': 728,
     'xp_start': 7038,
     'xp_end': 7766},
    {'deaths_pos': {},
     'ability_uses': {'rubick_spell_steal': 1},
     'ability_targets': {},
     'item_uses': {'tpscroll': 1},