# Deploy Pro Matches Model

In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
from sklearn.linear_model import LogisticRegression

from dota_oracle_common.models.features.schema import TeamFeaturesHyperparams, PlayerHeroFeaturesHyperparams, HeroFeaturesHyperparams
from dota_oracle_common.postgresql import DatabaseManager

from dota_oracle_pipeline.feature_engineering.batch.hero_wr_features.decay import HeroWinrateDecayFeatureGenerator
from dota_oracle_pipeline.feature_engineering.batch.player_hero_features.dynamic_prior import PlayerHeroDynamicPriorFeatureGenerator
from dota_oracle_pipeline.feature_engineering.batch.team_features.decay import TeamDecayFeatureGenerator

from dota_oracle_pipeline.feature_transformation.aggregate_features import create_final_features

In [3]:
TEAM_FEATURES_HYPERPARAMS = TeamFeaturesHyperparams(
    prior_mean=0.52, prior_count=13, half_life_days=45
)

HERO_FEATURES_HYPERPARAMS = HeroFeaturesHyperparams(
    prior_mean=0.5, prior_count=50, half_life_days=45
)

PLAYER_HERO_FEATURES_HYPERPARAMS = PlayerHeroFeaturesHyperparams(
    player_prior_count=8,
    player_half_life_days=60, 
    hero_prior_count=50,
    hero_prior_mean=0.5,
    hero_half_life_days=45
)

In [4]:
local_session = DatabaseManager.get_session_factory()

2025-11-04 04:13:33,742 - dota_oracle_common.postgresql - INFO - Creating database engine with pool_size=10 and max_overflow=5

2025-11-04 04:13:33,780 - dota_oracle_common.postgresql - INFO - Successfully initialized database for 'dota2' at localhost

In [5]:
from dota_oracle_schedules.ml_pipelines.backfill_feature_engineering import get_all_matches, filter_completed_matches

In [6]:
async with local_session() as db_session:
    # Memory bottleneck to consider when number of matches is very large. Change batch processing to stateful generators later. 
    all_historical_matches = await get_all_matches(db_session)
    sorted_matches = sorted(all_historical_matches, key=lambda x: x.start_time)
    completed_matches = filter_completed_matches(sorted_matches)
    
completed_matches[:100]

2025-11-04 04:13:37,991 - dota_oracle_schedules.ml_pipelines.backfill_feature_engineering - INFO - Fetching all match details from the database...
2025-11-04 04:13:49,541 - dota_oracle_common.repositories.base_repository - INFO - Retrieved 127694 records for MatchTable
2025-11-04 04:13:49,542 - dota_oracle_common.repositories.match_repository - INFO - Found 127694 MatchTable details.
2025-11-04 04:13:49,543 - dota_oracle_schedules.ml_pipelines.backfill_feature_engineering - INFO - Fetched 127694 matches from the database.

[MatchTable(slot_129_hero_id=54, slot_0_account_id=452400903, slot_131_account_id=194521913, slot_0_hero_id=42, slot_130_hero_id=7, slot_132_account_id=278770268, slot_131_hero_id=98, slot_2_account_id=493967542, radiant_team_id=8254112, slot_1_hero_id=30, slot_132_hero_id=121, slot_3_account_id=455509466, dire_team_id=8252786, slot_2_hero_id=107, match_id=5999176266, slot_4_account_id=413339999, start_time=datetime.datetime(2021, 5, 17, 21, 6, 51, tzinfo=datetime.timezone.utc), slot_3_hero_id=52, slot_128_account_id=116293223, radiant_name='Omega Gaming', dire_name='Incubus Gaming', slot_4_hero_id=55, slot_129_account_id=173971950, duration=2398.0, slot_128_hero_id=65, leagueid=None, slot_1_account_id=294218576, slot_130_account_id=101779337),
 MatchTable(slot_129_hero_id=17, slot_0_account_id=86818655, slot_131_account_id=184131721, slot_0_hero_id=68, slot_130_hero_id=61, slot_132_account_id=107579895, slot_131_hero_id=88, slot_2_account_id=126174633, radiant_team_id=8375259, slot_1_hero_id=58, slot_132_hero_id=6, slot_3_account_id=88611330, dire_team_id=8254387, slot_2_hero_id=97, match_id=5999201501, slot_4_account_id=203851397, start_time=datetime.datetime(2021, 5, 17, 21, 40, 35, tzinfo=datetime.timezone.utc), slot_3_hero_id=106, slot_128_account_id=97366926, radiant_name='Infinity', dire_name='Crewmates', slot_4_hero_id=19, slot_129_account_id=97072681, duration=1784.0, slot_128_hero_id=111, leagueid=None, slot_1_account_id=916319073, slot_130_account_id=71266407),
 MatchTable(slot_129_hero_id=2, slot_0_account_id=118207269, slot_131_account_id=79818006, slot_0_hero_id=96, slot_130_hero_id=94, slot_132_account_id=67893845, slot_131_hero_id=128, slot_2_account_id=230580807, radiant_team_id=7101094, slot_1_hero_id=123, slot_132_hero_id=30, slot_3_account_id=76600360, dire_team_id=8261882, slot_2_hero_id=15, match_id=5999214195, slot_4_account_id=318588173, start_time=datetime.datetime(2021, 5, 17, 22, 2, 1, tzinfo=datetime.timezone.utc), slot_3_hero_id=121, slot_128_account_id=874542740, radiant_name='Wind and Rain', dire_name='felt', slot_4_hero_id=72, slot_129_account_id=93159453, duration=1793.0, slot_128_hero_id=23, leagueid=None, slot_1_account_id=126469785, slot_130_account_id=172739956),
 MatchTable(slot_129_hero_id=96, slot_0_account_id=874542740, slot_131_account_id=318588173, slot_0_hero_id=126, slot_130_hero_id=106, slot_132_account_id=76600360, slot_131_hero_id=94, slot_2_account_id=172739956, radiant_team_id=8261882, slot_1_hero_id=78, slot_132_hero_id=68, slot_3_account_id=79818006, dire_team_id=7101094, slot_2_hero_id=109, match_id=5999249937, slot_4_account_id=67893845, start_time=datetime.datetime(2021, 5, 17, 23, 2, 25, tzinfo=datetime.timezone.utc), slot_3_hero_id=128, slot_128_account_id=126469785, radiant_name='felt', dire_name='Wind and Rain', slot_4_hero_id=102, slot_129_account_id=118207269, duration=1702.0, slot_128_hero_id=86, leagueid=None, slot_1_account_id=93159453, slot_130_account_id=230580807),
 MatchTable(slot_129_hero_id=68, slot_0_account_id=126469785, slot_131_account_id=79818006, slot_0_hero_id=58, slot_130_hero_id=96, slot_132_account_id=172739956, slot_131_hero_id=128, slot_2_account_id=230580807, radiant_team_id=7101094, slot_1_hero_id=98, slot_132_hero_id=46, slot_3_account_id=318588173, dire_team_id=8261882, slot_2_hero_id=19, match_id=5999283181, slot_4_account_id=76600360, start_time=datetime.datetime(2021, 5, 18, 0, 2, 6, tzinfo=datetime.timezone.utc), slot_3_hero_id=42, slot_128_account_id=874542740, radiant_name='Wind and Rain', dire_name='felt', slot_4_hero_id=111, slot_129_account_id=67893845, duration=1606.0, slot_128_hero_id=41, leagueid=None, slot_1_account_id=118207269, slot_130_account_id=93159453),
 MatchTable(slot_129_hero_id=26, slot_0_account_id=877696078, slot_131_account_id=165839292, slot_0_hero_id=19, slot_130_hero_id=11, slot_132_account_id=177455231, slot_131_hero_id=96, slot_2_account_id=318286721, radiant_team_id=7653080, slot_1_hero_id=86, slot_132_hero_id=102, slot_3_account_id=160708663, dire_team_id=8374615, slot_2_hero_id=129, match_id=5999407636, slot_4_account_id=360648679, start_time=datetime.datetime(2021, 5, 18, 3, 19, 31, tzinfo=datetime.timezone.utc), slot_3_hero_id=68, slot_128_account_id=236322966, radiant_name='Yangon Galacticos', dire_name='5CATS', slot_4_hero_id=12, slot_129_account_id=396365450, duration=1380.0, slot_128_hero_id=94, leagueid=None, slot_1_account_id=318371533, slot_130_account_id=144733344),
 MatchTable(slot_129_hero_id=100, slot_0_account_id=150970092, slot_131_account_id=217386639, slot_0_hero_id=17, slot_130_hero_id=19, slot_132_account_id=136624722, slot_131_hero_id=60, slot_2_account_id=106767376, radiant_team_id=8261500, slot_1_hero_id=95, slot_132_hero_id=103, slot_3_account_id=925571030, dire_team_id=8254195, slot_2_hero_id=26, match_id=5999433909, slot_4_account_id=135492698, start_time=datetime.datetime(2021, 5, 18, 3, 56, 18, tzinfo=datetime.timezone.utc), slot_3_hero_id=88, slot_128_account_id=102185479, radiant_name='Xtreme Gaming', dire_name='Demon Slayer', slot_4_hero_id=104, slot_129_account_id=141010367, duration=1893.0, slot_128_hero_id=94, leagueid=None, slot_1_account_id=246523528, slot_130_account_id=230617400),
 MatchTable(slot_129_hero_id=107, slot_0_account_id=236322966, slot_131_account_id=160708663, slot_0_hero_id=6, slot_130_hero_id=47, slot_132_account_id=360648679, slot_131_hero_id=111, slot_2_account_id=144733344, radiant_team_id=8374615, slot_1_hero_id=37, slot_132_hero_id=67, slot_3_account_id=396365450, dire_team_id=7653080, slot_2_hero_id=17, match_id=5999441172, slot_4_account_id=165839292, start_time=datetime.datetime(2021, 5, 18, 4, 6, 31, tzinfo=datetime.timezone.utc), slot_3_hero_id=86, slot_128_account_id=877696078, radiant_name='5CATS', dire_name='Yangon Galacticos', slot_4_hero_id=96, slot_129_account_id=318371533, duration=1581.0, slot_128_hero_id=52, leagueid=None, slot_1_account_id=177455231, slot_130_account_id=318286721),
 MatchTable(slot_129_hero_id=129, slot_0_account_id=102185479, slot_131_account_id=925571030, slot_0_hero_id=70, slot_130_hero_id=119, slot_132_account_id=246523528, slot_131_hero_id=103, slot_2_account_id=141010367, radiant_team_id=8254195, slot_1_hero_id=98, slot_132_hero_id=41, slot_3_account_id=230617400, dire_team_id=8261500, slot_2_hero_id=58, match_id=5999477345, slot_4_account_id=136624722, start_time=datetime.datetime(2021, 5, 18, 4, 54, 55, tzinfo=datetime.timezone.utc), slot_3_hero_id=99, slot_128_account_id=150970092, radiant_name='Demon Slayer', dire_name='Xtreme Gaming', slot_4_hero_id=26, slot_129_account_id=135492698, duration=1572.0, slot_128_hero_id=25, leagueid=None, slot_1_account_id=217386639, slot_130_account_id=106767376),
 MatchTable(slot_129_hero_id=26, slot_0_account_id=164530809, slot_131_account_id=184138153, slot_0_hero_id=128, slot_130_hero_id=52, slot_132_account_id=392565237, slot_131_hero_id=96, slot_2_account_id=242837510, radiant_team_id=8124688, slot_1_hero_id=129, slot_132_hero_id=32, slot_3_account_id=135656964, dire_team_id=8261197, slot_2_hero_id=13, match_id=5999485249, slot_4_account_id=208796906, start_time=datetime.datetime(2021, 5, 18, 5, 7, 2, tzinfo=datetime.timezone.utc), slot_3_hero_id=51, slot_128_account_id=58429537, radiant_name='Kylin Esports Club', dire_name='Motivate.Trust Gaming', slot_4_hero_id=18, slot_129_account_id=193815691, duration=1972.0, slot_128_hero_id=111, leagueid=None, slot_1_account_id=223344914, slot_130_account_id=104758571),
 MatchTable(slot_129_hero_id=26, slot_0_account_id=150970092, slot_131_account_id=230617400, slot_0_hero_id=39, slot_130_hero_id=29, slot_132_account_id=136624722, slot_131_hero_id=19, slot_2_account_id=106767376, radiant_team_id=8261500, slot_1_hero_id=120, slot_132_hero_id=51, slot_3_account_id=246523528, dire_team_id=8254195, slot_2_hero_id=128, match_id=5999512934, slot_4_account_id=925571030, start_time=datetime.datetime(2021, 5, 18, 5, 42, 44, tzinfo=datetime.timezone.utc), slot_3_hero_id=41, slot_128_account_id=102185479, radiant_name='Xtreme Gaming', dire_name='Demon Slayer', slot_4_hero_id=30, slot_129_account_id=141010367, duration=2129.0, slot_128_hero_id=10, leagueid=None, slot_1_account_id=135492698, slot_130_account_id=217386639),
 MatchTable(slot_129_hero_id=52, slot_0_account_id=148215639, slot_131_account_id=134276083, slot_0_hero_id=10, slot_130_hero_id=26, slot_132_account_id=143693439, slot_131_hero_id=96, slot_2_account_id=207829314, radiant_team_id=6209166, slot_1_hero_id=83, slot_132_hero_id=110, slot_3_account_id=129958758, dire_team_id=726228, slot_2_hero_id=9, match_id=5999526271, slot_4_account_id=373520478, start_time=datetime.datetime(2021, 5, 18, 6, 0, 46, tzinfo=datetime.timezone.utc), slot_3_hero_id=29, slot_128_account_id=277141004, radiant_name='Team Aster', dire_name='Vici Gaming', slot_4_hero_id=15, slot_129_account_id=107803494, duration=3010.0, slot_128_hero_id=2, leagueid=None, slot_1_account_id=89423756, slot_130_account_id=138543123),
 MatchTable(slot_129_hero_id=128, slot_0_account_id=164530809, slot_131_account_id=184138153, slot_0_hero_id=107, slot_130_hero_id=13, slot_132_account_id=392565237, slot_131_hero_id=16, slot_2_account_id=135656964, radiant_team_id=8124688, slot_1_hero_id=52, slot_132_hero_id=94, slot_3_account_id=223344914, dire_team_id=8261197, slot_2_hero_id=102, match_id=5999530395, slot_4_account_id=208796906, start_time=datetime.datetime(2021, 5, 18, 6, 6, 11, tzinfo=datetime.timezone.utc), slot_3_hero_id=55, slot_128_account_id=58429537, radiant_name='Kylin Esports Club', dire_name='Motivate.Trust Gaming', slot_4_hero_id=19, slot_129_account_id=193815691, duration=1430.0, slot_128_hero_id=103, leagueid=None, slot_1_account_id=242837510, slot_130_account_id=104758571),
 MatchTable(slot_129_hero_id=70, slot_0_account_id=58429537, slot_131_account_id=242837510, slot_0_hero_id=85, slot_130_hero_id=87, slot_132_account_id=223344914, slot_131_hero_id=15, slot_2_account_id=104758571, radiant_team_id=8261197, slot_1_hero_id=88, slot_132_hero_id=120, slot_3_account_id=184138153, dire_team_id=8124688, slot_2_hero_id=65, match_id=5999563907, slot_4_account_id=392565237, start_time=datetime.datetime(2021, 5, 18, 6, 51, 2, tzinfo=datetime.timezone.utc), slot_3_hero_id=55, slot_128_account_id=164530809, radiant_name='Motivate.Trust Gaming', dire_name='Kylin Esports Club', slot_4_hero_id=94, slot_129_account_id=208796906, duration=2544.0, slot_128_hero_id=128, leagueid=None, slot_1_account_id=193815691, slot_130_account_id=135656964),
 MatchTable(slot_129_hero_id=98, slot_0_account_id=148215639, slot_131_account_id=143693439, slot_0_hero_id=93, slot_130_hero_id=11, slot_132_account_id=138543123, slot_131_hero_id=87, slot_2_account_id=129958758, radiant_team_id=6209166, slot_1_hero_id=26, slot_132_hero_id=88, slot_3_account_id=207829314, dire_team_id=726228, slot_2_hero_id=96, match_id=5999581275, slot_4_account_id=373520478, start_time=datetime.datetime(2021, 5, 18, 7, 11, 49, tzinfo=datetime.timezone.utc), slot_3_hero_id=91, slot_128_account_id=277141004, radiant_name='Team Aster', dire_name='Vici Gaming', slot_4_hero_id=46, slot_129_account_id=134276083, duration=2146.0, slot_128_hero_id=67, leagueid=None, slot_1_account_id=89423756, slot_130_account_id=107803494),
 MatchTable(slot_129_hero_id=8, slot_0_account_id=101259972, slot_131_account_id=94738847, slot_0_hero_id=26, slot_130_hero_id=25, slot_132_account_id=94296097, slot_131_hero_id=16, slot_2_account_id=168028715, radiant_team_id=5, slot_1_hero_id=52, slot_132_hero_id=121, slot_3_account_id=139876032, dire_team_id=4, slot_2_hero_id=42, match_id=5999590340, slot_4_account_id=138857296, start_time=datetime.datetime(2021, 5, 18, 7, 22, 28, tzinfo=datetime.timezone.utc), slot_3_hero_id=110, slot_128_account_id=182331313, radiant_name='INVICTUS GAMING', dire_name='EHOME', slot_4_hero_id=129, slot_129_account_id=108382060, duration=2419.0, slot_128_hero_id=128, leagueid=None, slot_1_account_id=202217968, slot_130_account_id=137129583),
 MatchTable(slot_129_hero_id=112, slot_0_account_id=230617400, slot_131_account_id=160708663, slot_0_hero_id=20, slot_130_hero_id=96, slot_132_account_id=360648679, slot_131_hero_id=128, slot_2_account_id=217386639, radiant_team_id=8254195, slot_1_hero_id=94, slot_132_hero_id=12, slot_3_account_id=141010367, dire_team_id=7653080, slot_2_hero_id=16, match_id=5999593680, slot_4_account_id=136624722, start_time=datetime.datetime(2021, 5, 18, 7, 26, 36, tzinfo=datetime.timezone.utc), slot_3_hero_id=9, slot_128_account_id=877696078, radiant_name='Demon Slayer', dire_name='Yangon Galacticos', slot_4_hero_id=58, slot_129_account_id=318371533, duration=1637.0, slot_128_hero_id=19, leagueid=None, slot_1_account_id=102185479, slot_130_account_id=318286721),
 MatchTable(slot_129_hero_id=19, slot_0_account_id=130503714, slot_131_account_id=209287073, slot_0_hero_id=26, slot_130_hero_id=43, slot_132_account_id=392169957, slot_131_hero_id=88, slot_2_account_id=136642777, radiant_team_id=8272008, slot_1_hero_id=46, slot_132_hero_id=13, slot_3_account_id=1071549996, dire_team_id=8169775, slot_2_hero_id=78, match_id=5999622638, slot_4_account_id=185438531, start_time=datetime.datetime(2021, 5, 18, 8, 2, 28, tzinfo=datetime.timezone.utc), slot_3_hero_id=54, slot_128_account_id=274078636, radiant_name='Crocodile', dire_name='Geek Slate', slot_4_hero_id=102, slot_129_account_id=458287006, duration=2069.0, slot_128_hero_id=121, leagueid=None, slot_1_account_id=173880329, slot_130_account_id=451317002),
 MatchTable(slot_129_hero_id=58, slot_0_account_id=877696078, slot_131_account_id=141010367, slot_0_hero_id=106, slot_130_hero_id=8, slot_132_account_id=217386639, slot_131_hero_id=121, slot_2_account_id=318286721, radiant_team_id=7653080, slot_1_hero_id=51, slot_132_hero_id=129, slot_3_account_id=160708663, dire_team_id=8254195, slot_2_hero_id=128, match_id=5999630654, slot_4_account_id=360648679, start_time=datetime.datetime(2021, 5, 18, 8, 10, 14, tzinfo=datetime.timezone.utc), slot_3_hero_id=102, slot_128_account_id=230617400, radiant_name='Yangon Galacticos', dire_name='Demon Slayer', slot_4_hero_id=95, slot_129_account_id=136624722, duration=1713.0, slot_128_hero_id=46, leagueid=None, slot_1_account_id=318371533, slot_130_account_id=102185479),
 MatchTable(slot_129_hero_id=26, slot_0_account_id=137193239, slot_131_account_id=107803494, slot_0_hero_id=10, slot_130_hero_id=43, slot_132_account_id=134276083, slot_131_hero_id=46, slot_2_account_id=139937922, radiant_team_id=8204512, slot_1_hero_id=25, slot_132_hero_id=98, slot_3_account_id=101695162, dire_team_id=726228, slot_2_hero_id=16, match_id=5999641847, slot_4_account_id=108221389, start_time=datetime.datetime(2021, 5, 18, 8, 22, 58, tzinfo=datetime.timezone.utc), slot_3_hero_id=128, slot_128_account_id=277141004, radiant_name='Neptune Gaming', dire_name='Vici Gaming', slot_4_hero_id=51, slot_129_account_id=138543123, duration=3854.0, slot_128_hero_id=2, leagueid=None, slot_1_account_id=106863163, slot_130_account_id=143693439),
 MatchTable(slot_129_hero_id=43, slot_0_account_id=94738847, slot_131_account_id=202217968, slot_0_hero_id=29, slot_130_hero_id=26, slot_132_account_id=101259972, slot_131_hero_id=10, slot_2_account_id=94296097, radiant_team_id=4, slot_1_hero_id=6, slot_132_hero_id=83, slot_3_account_id=108382060, dire_team_id=5, slot_2_hero_id=100, match_id=5999656438, slot_4_account_id=182331313, start_time=datetime.datetime(2021, 5, 18, 8, 39, 9, tzinfo=datetime.timezone.utc), slot_3_hero_id=53, slot_128_account_id=138857296, radiant_name='EHOME', dire_name='INVICTUS GAMING', slot_4_hero_id=128, slot_129_account_id=168028715, duration=1663.0, slot_128_hero_id=2, leagueid=None, slot_1_account_id=137129583, slot_130_account_id=139876032),
 MatchTable(slot_129_hero_id=100, slot_0_account_id=209287073, slot_131_account_id=136642777, slot_0_hero_id=88, slot_130_hero_id=26, slot_132_account_id=1071549996, slot_131_hero_id=98, slot_2_account_id=451317002, radiant_team_id=8169775, slot_1_hero_id=121, slot_132_hero_id=72, slot_3_account_id=458287006, dire_team_id=8272008, slot_2_hero_id=36, match_id=5999676154, slot_4_account_id=392169957, start_time=datetime.datetime(2021, 5, 18, 9, 0, 44, tzinfo=datetime.timezone.utc), slot_3_hero_id=95, slot_128_account_id=173880329, radiant_name='Geek Slate', dire_name='Crocodile', slot_4_hero_id=19, slot_129_account_id=185438531, duration=1845.0, slot_128_hero_id=128, leagueid=None, slot_1_account_id=274078636, slot_130_account_id=130503714),
 MatchTable(slot_129_hero_id=26, slot_0_account_id=274078636, slot_131_account_id=1071549996, slot_0_hero_id=121, slot_130_hero_id=78, slot_132_account_id=185438531, slot_131_hero_id=8, slot_2_account_id=451317002, radiant_team_id=8169775, slot_1_hero_id=44, slot_132_hero_id=111, slot_3_account_id=209287073, dire_team_id=8272008, slot_2_hero_id=29, match_id=5999722122, slot_4_account_id=392169957, start_time=datetime.datetime(2021, 5, 18, 9, 51, 48, tzinfo=datetime.timezone.utc), slot_3_hero_id=107, slot_128_account_id=173880329, radiant_name='Geek Slate', dire_name='Crocodile', slot_4_hero_id=19, slot_129_account_id=130503714, duration=1507.0, slot_128_hero_id=97, leagueid=None, slot_1_account_id=458287006, slot_130_account_id=136642777),
 MatchTable(slot_129_hero_id=46, slot_0_account_id=277141004, slot_131_account_id=101695162, slot_0_hero_id=109, slot_130_hero_id=78, slot_132_account_id=108221389, slot_131_hero_id=43, slot_2_account_id=134276083, radiant_team_id=726228, slot_1_hero_id=128, slot_132_hero_id=84, slot_3_account_id=107803494, dire_team_id=8204512, slot_2_hero_id=96, match_id=5999723508, slot_4_account_id=143693439, start_time=datetime.datetime(2021, 5, 18, 9, 52, 4, tzinfo=datetime.timezone.utc), slot_3_hero_id=126, slot_128_account_id=137193239, radiant_name='Vici Gaming', dire_name='Neptune Gaming', slot_4_hero_id=79, slot_129_account_id=106863163, duration=2167.0, slot_128_hero_id=52, leagueid=None, slot_1_account_id=138543123, slot_130_account_id=139937922),
 MatchTable(slot_129_hero_id=47, slot_0_account_id=898754153, slot_131_account_id=119535307, slot_0_hero_id=41, slot_130_hero_id=98, slot_132_account_id=90882159, slot_131_hero_id=128, slot_2_account_id=118134220, radiant_team_id=15, slot_1_hero_id=25, slot_132_hero_id=103, slot_3_account_id=157475523, dire_team_id=6209804, slot_2_hero_id=81, match_id=5999726166, slot_4_account_id=111114687, start_time=datetime.datetime(2021, 5, 18, 9, 54, 47, tzinfo=datetime.timezone.utc), slot_3_hero_id=52, slot_128_account_id=136177710, radiant_name='PSG.LGD', dire_name='Antarctic Penguins', slot_4_hero_id=37, slot_129_account_id=134711350, duration=2072.0, slot_128_hero_id=42, leagueid=None, slot_1_account_id=173978074, slot_130_account_id=186627166),
 MatchTable(slot_129_hero_id=52, slot_0_account_id=277141004, slot_131_account_id=101695162, slot_0_hero_id=54, slot_130_hero_id=2, slot_132_account_id=108221389, slot_131_hero_id=43, slot_2_account_id=107803494, radiant_team_id=726228, slot_1_hero_id=128, slot_132_hero_id=84, slot_3_account_id=138543123, dire_team_id=8204512, slot_2_hero_id=126, match_id=5999785840, slot_4_account_id=134276083, start_time=datetime.datetime(2021, 5, 18, 10, 54, 30, tzinfo=datetime.timezone.utc), slot_3_hero_id=79, slot_128_account_id=137193239, radiant_name='Vici Gaming', dire_name='Neptune Gaming', slot_4_hero_id=99, slot_129_account_id=106863163, duration=1908.0, slot_128_hero_id=63, leagueid=None, slot_1_account_id=143693439, slot_130_account_id=139937922),

In [7]:
train_percentage = 0.8
train_size = int(len(completed_matches) * train_percentage)
train_matches = completed_matches[:train_size]
test_matches = completed_matches[train_size:]
print(f"Train matches: {len(train_matches)}, Test matches: {len(test_matches)}")

train_ids_set = set([match.match_id for match in train_matches])
test_ids_set = set([match.match_id for match in test_matches])

Train matches: 101324, Test matches: 25331

In [8]:
hero_generator = HeroWinrateDecayFeatureGenerator()
hero_features = hero_generator.generate_wide_format(
    completed_matches,
    prior_mean=HERO_FEATURES_HYPERPARAMS.prior_mean,
    prior_count=HERO_FEATURES_HYPERPARAMS.prior_count,
    half_life_days=HERO_FEATURES_HYPERPARAMS.half_life_days,
)


player_hero_generator = PlayerHeroDynamicPriorFeatureGenerator()
player_hero_features = player_hero_generator.generate(
    completed_matches,
    player_prior_count=PLAYER_HERO_FEATURES_HYPERPARAMS.player_prior_count,
    player_half_life_days=PLAYER_HERO_FEATURES_HYPERPARAMS.player_half_life_days,
    hero_prior_count=PLAYER_HERO_FEATURES_HYPERPARAMS.hero_prior_count,
    hero_prior_mean=PLAYER_HERO_FEATURES_HYPERPARAMS.hero_prior_mean,
    hero_half_life_days=PLAYER_HERO_FEATURES_HYPERPARAMS.hero_half_life_days,
)
        
team_generator = TeamDecayFeatureGenerator()
team_features = team_generator.generate(
    completed_matches,
    prior_mean=TEAM_FEATURES_HYPERPARAMS.prior_mean,
    prior_count=TEAM_FEATURES_HYPERPARAMS.prior_count,
    half_life_days=TEAM_FEATURES_HYPERPARAMS.half_life_days,
)

Step 1/2: Generating dynamic hero priors...
Hero priors generated.
Step 2/2: Generating player-hero features with dynamic priors...
Player-hero features generated.

In [9]:
import pandas as pd

In [10]:
aggregated_features = create_final_features(
    hero_features_list=hero_features,
    player_hero_features_list=player_hero_features,
    team_features_list=team_features,
)

['match_id', 'radiant_dire_team_wr_diff', 'radiant_dire_matchup', 'radiant_dire_player_wr_diff', 'radiant_dire_hero_wr_diff']

In [11]:
final_features_df = pd.DataFrame([feat.model_dump() for feat in aggregated_features])
final_features_df

,match_id,radiant_dire_team_wr_diff,radiant_dire_matchup,radiant_dire_player_wr_diff,radiant_dire_hero_wr_diff
0,5999176266,0.000000,0.520000,0.000000,0.000000
1,5999201501,0.000000,0.520000,0.000000,0.000000
2,5999214195,0.000000,0.520000,-0.003919,-0.003919
3,5999249937,0.071386,0.517121,0.019819,-0.001959
4,5999283181,0.000043,0.517357,-0.001880,-0.001884
...,...,...,...,...,...
126650,8541987656,-0.056029,0.520000,-0.013221,0.000608
126651,8542008481,0.000000,0.520000,0.019723,0.019723
126652,8542042026,0.076770,0.520000,0.059289,-0.012409
126653,8542050104,-0.118197,0.482875,0.020261,0.003676
126654,8542063992,-0.071400,0.445728,-0.010566,0.001281

In [12]:
match_outcomes = [match.outcome for match in completed_matches if match.outcome is not None]
match_outcomes_df = pd.DataFrame([match.model_dump() for match in match_outcomes])

match_outcomes_df

        radiant_win    match_id
0              True  5999176266
1              True  5999201501
2             False  5999214195
3             False  5999249937
4             False  5999283181
...             ...         ...
126650        False  8541987656
126651         True  8542008481
126652         True  8542042026
126653         True  8542050104
126654        False  8542063992

[126655 rows x 2 columns]

In [13]:
final_df = pd.merge(final_features_df, match_outcomes_df, on="match_id")

train_df = final_df[final_df['match_id'].isin(train_ids_set)]
test_df = final_df[final_df['match_id'].isin(test_ids_set)]

len(train_df), len(test_df)

(101324, 25331)

In [14]:
X_train = train_df.drop(columns=["match_id", "radiant_win"])
y_train = train_df["radiant_win"]
X_test = test_df.drop(columns=["match_id", "radiant_win"])
y_test = test_df["radiant_win"]

len(X_train), len(X_test), len(y_train), len(y_test)

(101324, 25331, 101324, 25331)

In [15]:
log_model = LogisticRegression(random_state=42, max_iter=1000)

In [21]:
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss

In [20]:
log_model.fit(X_train, y_train)

y_pred = log_model.predict(X_test)
y_predict_proba = log_model.predict_proba(X_test)[:, 1]

In [22]:
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_predict_proba)
log_loss_value = log_loss(y_test, y_predict_proba)

print(f"Accuracy: {accuracy:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")
print(f"Log Loss: {log_loss_value:.4f}")

Accuracy: 0.5763
ROC AUC: 0.6034
Log Loss: 0.6751

In [10]:
hero_feature_creator = HeroesFeatureCreator(
    prior_mean=hero_features_hyperparams.prior_mean,
    prior_count=hero_features_hyperparams.prior_count,
    half_life_days=hero_features_hyperparams.half_life_days,
)
team_feature_creator = TeamFeatureCreator(
    prior_mean=team_features_hyperparams.prior_mean,
    prior_count=team_features_hyperparams.prior_count,
    half_life_days=team_features_hyperparams.half_life_days,
)
player_hero_feature_creator = PlayerHeroFeaturesCreator(
    player_prior_count=player_hero_features_hyperparams.player_prior_count,
    player_half_life_days=player_hero_features_hyperparams.player_half_life_days,
    hero_prior_count=player_hero_features_hyperparams.hero_prior_count,
    hero_prior_mean=player_hero_features_hyperparams.hero_prior_mean,
    hero_half_life_days=player_hero_features_hyperparams.hero_half_life_days,
)